In [41]:
import pandas as pd #pd.DataFrame(), Pandas.DataFrame()
import numpy as np
#from pandas import * # *쓰면 전부다 불러온다. 그러면 메모리 낭비 심하다. 
from pandas import DataFrame #이렇게 하는게 효율적.
#from pandas import * #DataFrame()

In [38]:
# pd.DataFrame() #pandas 안에서 함수는 부를수있다.
#DataFrame.to_csv()# 이렇게는 안된다.

Empty DataFrame
Columns: []
Index: []

In [12]:
#json 딕셔너리로 저장, pickle 객체단위로 저장. 바이너리 형태로 저장. why? 속도가 빠르고 쉽게 불러올수있다.
pd.read_csv("test_text.txt", sep="|")
#행 인덱스(왼쪽), 열 인덱스(위쪽)
#디폴트 행 인덱스: 0번~
pd.read_csv("test_text.txt", sep="|", index_col='ID')
pd.read_csv("test_text.txt", sep="|", index_col=2)# 번호에 해당하는 인덱스가 행이 바뀌고, 구분하는 용도로 사용가능




ID LAST_NAME
AGE              
25    1       KIM
22    2       LEE
33    3      PARK
24    4      CHOI
30    5       CHO

In [15]:
pd.read_csv("test_text_without_name.txt", sep="|", index_col=0)
#kim 25는 데이터인데, 열 인덱스로 읽어버렸다.
#header= 있음, defalut 디폴트 설정되어 있음.
pd.read_csv("test_text_without_name.txt", header=None, sep="|", index_col=0)
#데이터는 그대로 나온다. 열 인덱스부분엔 자동으로 숫자 0,1, 2 붙는다. 바꿀수있다.
#header 위치를 다른곳에 적더라도 상관없다. 대신 txt 앞으로 나오면 안된다. 
#함수를 호출할때 첫번째 인수는 읽어 들이고자 하는 "파일의 이름", 속성의 이름은 정해져있다. sep, header


1   2
0          
1   KIM  25
2   LEE  22
3  PARK  33
4  CHOI  24
5   CHO  30

In [26]:
pd.read_csv("test_text.txt", sep="|", skiprows=2)
#연속적으로 여러 줄을 건너뛸 경우

pd.read_csv("test_text.txt", sep="|", skiprows=[0,2])
#비연속적으로 여러 줄을 건너뛸 경우

data=pd.read_csv("test_text.txt", sep="|", nrows=3)
#3줄만 불러오기(부분적으로 불러오기)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
ID           3 non-null int64
LAST_NAME    3 non-null object
AGE          3 non-null int64
dtypes: int64(2), object(1)
memory usage: 200.0+ bytes


In [28]:
#결측값: 값이 누락된 것. 무조건 제거하는게 좋은게 아니다. 대체할수있으면 대체 하는편이 좋다.
data=pd.read_csv("test_text_na.txt",sep="|")
#Pandas에서 object 나온게 -> string이다. 숫자로만 나오다가도 하나라도 문자가 나오면 object
data.info()
data




<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
ID           5 non-null int64
LAST_NAME    5 non-null object
AGE          5 non-null object
dtypes: int64(1), object(2)
memory usage: 248.0+ bytes


ID LAST_NAME AGE
0   1       KIM  25
1   2       LEE  없음
2   3      PARK  33
3   4        모름  24
4   5       CHO  30

In [30]:
data=pd.read_csv("test_text_na.txt",sep="|", na_values= ["없음","모름"]) #na -> not avabilable.
data.info() #float64 실수형으로 바뀐다. 
data


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
ID           5 non-null int64
LAST_NAME    4 non-null object
AGE          4 non-null float64
dtypes: float64(1), int64(1), object(1)
memory usage: 248.0+ bytes


ID LAST_NAME   AGE
0   1       KIM  25.0
1   2       LEE   NaN
2   3      PARK  33.0
3   4       NaN  24.0
4   5       CHO  30.0

In [35]:
data=pd.read_csv("test_text.txt",sep="|",
                dtype={'ID':int,
                      'LAST_NAME':str,
                      'AGE':str})
data.info() 
data


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
ID           5 non-null int32
LAST_NAME    5 non-null object
AGE          5 non-null object
dtypes: int32(1), object(2)
memory usage: 228.0+ bytes


ID LAST_NAME AGE
0   1       KIM  25
1   2       LEE  22
2   3      PARK  33
3   4      CHOI  24
4   5       CHO  30

In [44]:
from pandas import DataFrame

#딕셔너리 데이터로 데이터프레임 생성하기
df=DataFrame({
    'id':['a1','a2','a3','a4','a5'],
    'x1':[1,2,3,4,5],
    'x2':[1.1,2.2,3.3,4.4,5.5]    
})

#DataFrame.to_csv함수: 데이터프레임을 csv로 저장
df

id  x1   x2
0  a1   1  1.1
1  a2   2  2.2
2  a3   3  3.3
3  a4   4  4.4
4  a5   5  5.5

In [47]:
from pandas import DataFrame
#함수명(인수1,인수2,인수3)
#딕셔너리 데이터로 데이터프레임 생성하기
df=DataFrame(data={ #data={} 빼서 표현한것, 그래도 상관없다.
    'id':['a1','a2','a3','a4','a5'],
    'x1':[1,2,3,4,5],
    'x2':[1.1,2.2,3.3,4.4,5.5]    
}, index=['a','b','c','d','e'])

#DataFrame.to_csv함수: 데이터프레임을 csv로 저장
df

id  x1   x2
a  a1   1  1.1
b  a2   2  2.2
c  a3   3  3.3
d  a4   4  4.4
e  a5   5  5.5

In [54]:
from pandas import DataFrame

df=DataFrame(data={ 
    'id':['a1','a2','a3','a4','a5'],
    'x1':[1,2,3,4,5],
    'x2':[1.1,2.2,3.3,4.4,5.5]    
}, index=['a','b','c','d','e'])
df

#결측값으로 구성된 새로운 행 추가
df2=df.reindex(['a','b','c','d','e','f'])
df2

df=df.reindex(['a','k','c','e','f'])
df

id   x1   x2
a   a1  1.0  1.1
k  NaN  NaN  NaN
c   a3  3.0  3.3
e   a5  5.0  5.5
f  NaN  NaN  NaN

In [55]:
df2.to_csv("df2.csv")

In [56]:
df2.to_csv("df3.csv", sep="$")

In [60]:
df2.to_csv("df4.csv", na_rep='NaN', header=None)

In [59]:
df2

id   x1   x2
a   a1  1.0  1.1
b   a2  2.0  2.2
c   a3  3.0  3.3
d   a4  4.0  4.4
e   a5  5.0  5.5
f  NaN  NaN  NaN

In [61]:
df2.to_csv("df4.csv", na_rep='NaN', float_format="%.2f")# 소수점 2번째 자리까지.

In [ ]:
df2.to_csv("df4.csv", na_rep='NaN', float_format="%.2f")

In [63]:
df2.to_csv("df5.csv", na_rep='NaN', columns=['id','x2']) 
#답안 제출할때 이렇게 해야한다. 잘 알고 있어야 한다.

In [64]:
df2.to_csv("df6.csv", na_rep='NaN', columns=['id','x2'], index=False) 
#파일 읽고 저장하는것. 용법 기억해놓기. 저장 옵션. API 분석하면 좋다.

In [76]:
from pandas import DataFrame as df


In [85]:
#데이터프레임 만드는 다른 방법
df1=df(data=np.arange(8).reshape(4,2),  #data= 있어도 되고 없어도 된다
  columns=['col0','col1'],
  index=['row0','row1','row2','row3']) #dtype 설정 가능 int, str 이런것
type(df1) #pandas.core.frame.DataFrame

pandas.core.frame.DataFrame

In [86]:
df1
#transpose matrix #전치행렬

col0  col1
row0     0     1
row1     2     3
row2     4     5
row3     6     7

In [88]:
df1.T #
df1

col0  col1
row0     0     1
row1     2     3
row2     4     5
row3     6     7

In [89]:
df1.axes #axis(축, 단수), axes(복수)

[Index(['row0', 'row1', 'row2', 'row3'], dtype='object'),
 Index(['col0', 'col1'], dtype='object')]

In [90]:
df1.dtypes

col0    int32
col1    int32
dtype: object

In [91]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, row0 to row3
Data columns (total 2 columns):
col0    4 non-null int32
col1    4 non-null int32
dtypes: int32(2)
memory usage: 224.0+ bytes


In [92]:
df1.shape # tuple로 나온다. #꼭 집어야 자료의 모양을 알수있다.

(4, 2)

In [93]:
df1.T.shape

(2, 4)

In [96]:
df1.shape[0] #0은 행 -> 데이터 건수, 자료의 갯수. 열 -> 변수의 의미, 속성.

4

In [97]:
df1.size # 8=4*2

8

In [98]:
df1.values

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [102]:
np.random.randn(5) #평균 :0, 표준편차:1인 분포로부터 난수 발생

array([-0.01758247, -0.06064575, -0.87167867, -1.95992254,  0.1396879 ])

In [104]:
df=DataFrame({"cls_1":['a','a','b','b','c'],
         "v1":np.arange(5),
         "v2":np.random.randn(5)},
          index=['r0','r1','r2','r3','r4']
         )

In [105]:
df.index #행 인덱스가 출력.

Index(['r0', 'r1', 'r2', 'r3', 'r4'], dtype='object')

In [106]:
df.ix


C:\Users\student\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


In [107]:
df

cls_1  v1        v2
r0     a   0  1.192530
r1     a   1 -0.746977
r2     b   2 -0.059682
r3     b   3 -0.897817
r4     c   4  0.546651

In [115]:
import warnings
warnings.filterwarnings(action='ignore')

df.ix[0] #행 위치(0번부터 시작)
df.ix['r2']#행 인덱스 이름을 줘도 참조 가능
#ix는 행 단위 indexing할때, 
#행 위치(정수)와 행 인덱스 이름을 모두 사용할 수 있다.

#인덱스 3번부터 마지막까지 추출
df.ix[3:]
df.ix['r3':]

cls_1  v1        v2
r3     b   3 -0.897817
r4     c   4  0.546651

In [118]:
df
df.head(3) #head 맨위에서 3개 출력
df.tail(3)# 맨 아래에서 3개  출력

cls_1  v1        v2
r2     b   2 -0.059682
r3     b   3 -0.897817
r4     c   4  0.546651

In [120]:
df['cls_1']
df.cls_1

r0    a
r1    a
r2    b
r3    b
r4    c
Name: cls_1, dtype: object

In [131]:
type(df[['cls_1']])#pandas.core.frame.DataFrame 한개 이상일땐 대괄호 기호 2개쓴다. 열 수정
type(df['cls_1'])#pandas.core.series.Series



pandas.core.series.Series

In [137]:
#행 인덱스:r3,r4 제거, r5,r6가 추가

df.reindex(['r0','r1','r2','r5','r6'],fill_value=0)
df.reindex(['r0','r1','r2','r5','r6'],fill_value='missing')
df.reindex(['r0','r1','r2','r5','r6'],fill_value='NA')




cls_1  v1         v2
r0     a   0    1.19253
r1     a   1  -0.746977
r2     b   2 -0.0596822
r5    NA  NA         NA
r6    NA  NA         NA

In [159]:
#시계열 데이터:DataFrame에서 index를 만들때 date_range함수,시간에 따라 분배
date_idx=pd.date_range("1/7/2020",periods=5, freq="D")
#index 붙어있으므로, 행인덱스로 사용할 수 있게누나 하고 알수 있다.
#[ns] nano second. 10억분의 1, freq = 'D'->Day
#주식예측할떄 RNN. 이거 사용 시계열 데이터. 날짜 데이터로 행인덱스 사용하기 위해
date_idx


DatetimeIndex(['2020-01-07', '2020-01-08', '2020-01-09', '2020-01-10',
               '2020-01-11'],
              dtype='datetime64[ns]', freq='D')

In [147]:
df2=pd.DataFrame({"c1":[5,3,7,6,4]}) #DataFrame 딕셔너리 구조로. 행인텍스 사냥가능, 
df2

c1
0   5
1   3
2   7
3   6
4   4

In [148]:
df2=pd.DataFrame({"c1":[5,3,7,6,4]},index=date_idx) 
df2

c1
2020-01-07   5
2020-01-08   3
2020-01-09   7
2020-01-10   6
2020-01-11   4

In [154]:
date_idx2=pd.date_range("1/1/2020", periods=20, freq= "D")
date_idx2


DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12',
               '2020-01-13', '2020-01-14', '2020-01-15', '2020-01-16',
               '2020-01-17', '2020-01-18', '2020-01-19', '2020-01-20'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
df3=pd.DataFrame({"c1":[5,3,7,6,4]},index=date_idx2) df

In [157]:
df2.reindex(date_idx2, method="ffill") #마지막 데이터로부터 비워져있는것들이 밑으로 채워진다.
df2.reindex(date_idx2, method="bfill")# 위로 채워지는 방식. 위에서 처음 만나는 끊긴 데이터로.마지막 데이터로 채우는것, 





c1
2020-01-01  5.0
2020-01-02  5.0
2020-01-03  5.0
2020-01-04  5.0
2020-01-05  5.0
2020-01-06  5.0
2020-01-07  5.0
2020-01-08  3.0
2020-01-09  7.0
2020-01-10  6.0
2020-01-11  4.0
2020-01-12  NaN
2020-01-13  NaN
2020-01-14  NaN
2020-01-15  NaN
2020-01-16  NaN
2020-01-17  NaN
2020-01-18  NaN
2020-01-19  NaN
2020-01-20  NaN

In [8]:
#연습문제 패턴을 바로 적용할건지, 패턴을 설정해놓고 그다음 읽은 라인 쓰기. 둘다 연습.
#group, <?P(index)> 이거 공부하기. 
#문제 푸는데에 집중하기. 
from pandas import DataFrame
import re

with open('zoo.names', 'r') as f:
    line= f.readline()
    pat= re.compile("\s+{1,2}[.]\s\w+ )"
    pat.findall(line)

#zoo.names columns name list
df1=pd.read_csv("zoo.names",header =None) #header = None으로 해야 첫번째줄 올라가지 않음.


ParserError: Error tokenizing data. C error: Expected 1 fields in line 23, saw 7


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 18 columns):
aardvark    100 non-null object
1           100 non-null int64
0           100 non-null int64
0.1         100 non-null int64
1.1         100 non-null int64
0.2         100 non-null int64
0.3         100 non-null int64
1.2         100 non-null int64
1.3         100 non-null int64
1.4         100 non-null int64
1.5         100 non-null int64
0.4         100 non-null int64
0.5         100 non-null int64
4           100 non-null int64
0.6         100 non-null int64
0.7         100 non-null int64
1.6         100 non-null int64
1.7         100 non-null int64
dtypes: int64(17), object(1)
memory usage: 14.2+ KB


In [ ]:
import re
li_names=[]
with open("C:/Users/student/Downloads/Park_Jupyter/zoo.names",'r') as f:
    line = f.readline()
    line.



In [164]:
#문제2
boxData=[5,8,3,1,5,6,9,9,2,2,4]
boxData=np.array(boxData)
arr=[[0]*10]*11
arr=np.array(arr)
# for i in range(0,11):
#     for j in range(0,boxData[i]):
#         arr[i][j]=1
for i in range(0,10):
    print(boxData)
    print(max(boxData)-min(boxData))
    for j in range(0,11):
        if boxData[j]==max(boxData):
            boxData[j] = boxData[j]-1
            for k in range(0,11):     
                if boxData[k]==min(boxData):
                    boxData[k]+=1
                    break
            break

        

[5 8 3 1 5 6 9 9 2 2 4]
8
[5 8 3 2 5 6 8 9 2 2 4]
7
[5 8 3 3 5 6 8 8 2 2 4]
6
[5 7 3 3 5 6 8 8 3 2 4]
6
[5 7 3 3 5 6 7 8 3 3 4]
5
[5 7 4 3 5 6 7 7 3 3 4]
4
[5 6 4 4 5 6 7 7 3 3 4]
4
[5 6 4 4 5 6 6 7 4 3 4]
4
[5 6 4 4 5 6 6 6 4 4 4]
2
[5 5 5 4 5 6 6 6 4 4 4]
2


In [ ]:
#문제2
boxData=[5,8,3,1,5,6,9,9,2,2,4]
boxData=np.array(boxData)
input("")
arr=[[0]*10]*11
arr=np.array(arr)
# for i in range(0,11):
#     for j in range(0,boxData[i]):
#         arr[i][j]=1
for i in range(0,10):
    print(boxData)
    print(max(boxData)-min(boxData))
    for j in range(0,11):
        if boxData[j]==max(boxData):
            boxData[j] = boxData[j]-1
            for k in range(0,11):     
                if boxData[k]==min(boxData):
                    boxData[k]+=1
                    break
            break

In [166]:
10번의 평탄화 작업 이후 최고점과 최저점의 높이 차이

import numpy as np

box = [5,8,3,1,4,6,9,9,2,2,4]
N = 10

box = np.array(box)
max_n = max(box)
max_i = np.where(max_n == box)
max_i[0][0]
for i in range(N) :
  # 최고층, 최저층 index 추출
    max_n = max(box)
    max_i = np.where(max_n==box)
    min_n = min(box)
    min_i = np.where(min_n==box) # 최고점의 박스 하나가 빠지고
    box[max_i[0][0]] -= 1
    box[min_i[0][0]] += 1 # 최저점의 박스로 올라가는 과정
    
print('10번 시행 후 박스 =', box,'\n')

print("최고점과 최저점의 차이는 {} 입니다.".format(max(box) - min(box)))



10번 시행 후 박스 = [5 5 5 5 4 5 6 6 4 4 4] 

최고점과 최저점의 차이는 2 입니다.


In [7]:
import pandas as pd
from pandas import DataFrame
df = pd.read_csv('zoo.data', header=None)
df

# zoo.names에서 columns 목록 뽑아내기
import re
names_li = [] # columns 이름 저장할 리스트 생성
with open('zoo.names', 'r') as f :
    lines = f.readlines()
    lines.remove('\n')
    a = re.compile('\s+\d+[.]+\s+\w+') # 1. animal들 뽑는 정규식
    for line in lines :
        names = a.search(line)
        if names != None:
            n = names.group()
            names_li.append(re.search('[a-zA-Z]+',n).group()) # 숫자와 .빼고 영어부분만 추출
print(names_li) # 확인


df.columns = names_li # names_li로 df 속성 이름 변경

# df animal 부분을 빼고, 'age'를 넣은 후 0으로 채워넣기
df = df.reindex(columns = ['age','hair', 'feathers', 'eggs', 'milk',
                      'airborne', 'aquatic', 'predator', 'toothed', 'backbone',
                      'breathes', 'venomous', 'fins', 'legs', 'tail', 'domestic', 'catsize',
                           'type',], fill_value = 0)
# method = ffill, method = bfill 등을 넣을 수 있음

# 데이터 탐색 함수들..
df.head()
df.tail()
df.info()
df.shape
df.index

# 데이터 저장
df.to_csv('animal.csv', index=False)

['animal', 'hair', 'feathers', 'eggs', 'milk', 'airborne', 'aquatic', 'predator', 'toothed', 'backbone', 'breathes', 'venomous', 'fins', 'legs', 'tail', 'domestic', 'catsize', 'type']
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 18 columns):
age         101 non-null int64
hair        101 non-null int64
feathers    101 non-null int64
eggs        101 non-null int64
milk        101 non-null int64
airborne    101 non-null int64
aquatic     101 non-null int64
predator    101 non-null int64
toothed     101 non-null int64
backbone    101 non-null int64
breathes    101 non-null int64
venomous    101 non-null int64
fins        101 non-null int64
legs        101 non-null int64
tail        101 non-null int64
domestic    101 non-null int64
catsize     101 non-null int64
type        101 non-null int64
dtypes: int64(18)
memory usage: 14.3 KB


In [12]:
boxList=[5,8,3,1,5,6,9,9,2,2,4]
dump=int(input("Count dump: "))

for i in range(dump):
    boxList[boxList.index(max(boxList))] -= 1
    boxList[boxList.index(min(boxList))] += 1
    
print("Mix_height - Min_height:", max(boxList)-min(boxList))


Count dump: 10
Mix_height - Min_height: 2


In [ ]:
#count sort를 사용해보래.
#index를 바로 참조해서 카운팅하는 방법,
#해싱알고리즘-검색이 가장빠름(삼성)

