In [1]:
#pandas의 concat함수: 데이터프레임 합치기
# axis : {0/'index', 1/'columns'}, default 0
#         The axis to concatenate along.
#     join : {'inner', 'outer'}, default 'outer'
#         How to handle indexes on other axis (or axes).
#     join_axes : list of Index objects
#         .. deprecated:: 0.25.0
import pandas as pd




In [ ]:
help()


Welcome to Python 3.7's help utility!

If this is your first time using Python, you should definitely check out
the tutorial on the Internet at https://docs.python.org/3.7/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To quit this help utility and
return to the interpreter, just type "quit".

To get a list of available modules, keywords, symbols, or topics, type
"modules", "keywords", "symbols", or "topics".  Each module also comes
with a one-line summary of what it does; to list the modules whose name
or summary contain a given string such as "spam", type "modules spam".

help> pandas.concat
Help on function concat in pandas:

pandas.concat = concat(objs, axis=0, join='outer', join_axes=None, ignore_index=False, keys=None, levels=None, names=None, verify_integrity=False, sort=None, copy=True)
    Concatenate pandas objects along a particular axis with optional set logic
    along the other axes.
    
    

In [16]:
#자세한것은 pandas.pdf 파일 참조
df1=pd.DataFrame({'a':['a1','a2','a3'],
              'b':['b1','b2','b3'],
              'c':['c1','c2','c3'],
              'd':['d1','d2','d3'],
              }, index=[1,2,3])

df2=pd.DataFrame({'a':['a1','a2','a3'],
              'b':['b1','b2','b3'],
              'c':['c1','c2','c3'],
              'e':['d1','d2','d3'],
              }, index=[4,2,3])

In [17]:
df1

a   b   c   d
1  a1  b1  c1  d1
2  a2  b2  c2  d2
3  a3  b3  c3  d3

In [18]:
df2

a   b   c   e
4  a1  b1  c1  d1
2  a2  b2  c2  d2
3  a3  b3  c3  d3

In [19]:
df12=pd.concat([df1,df2], axis=1) 
#default: axis=0 (위아래로 합쳐짐) 열 인덱스 기준.
df12 #axis=1 좌우로 합쳐짐. 행 인덱스 기준.
#NaN이 보임.

a    b    c    d    a    b    c    e
1   a1   b1   c1   d1  NaN  NaN  NaN  NaN
2   a2   b2   c2   d2   a2   b2   c2   d2
3   a3   b3   c3   d3   a3   b3   c3   d3
4  NaN  NaN  NaN  NaN   a1   b1   c1   d1

In [20]:
df12=pd.concat([df1,df2], axis=0)
df12

C:\Users\student\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


a   b   c    d    e
1  a1  b1  c1   d1  NaN
2  a2  b2  c2   d2  NaN
3  a3  b3  c3   d3  NaN
4  a1  b1  c1  NaN   d1
2  a2  b2  c2  NaN   d2
3  a3  b3  c3  NaN   d3

In [21]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2'],
    'D': ['D0', 'D1', 'D2']},
    index=[0, 1, 2])

df2 = pd.DataFrame({'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5'],
    'D': ['D3', 'D4', 'D5']},
    index=[3, 4, 5])


In [22]:
df3=pd.concat([df1,df2], axis=0)
df3

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5

In [23]:
df3 = pd.DataFrame({'E': ['A6', 'A7', 'A8'],
    'F': ['B6', 'B7', 'B8'],
    'G': ['C6', 'C7', 'C8'],
    'H': ['D6', 'D7', 'D8']},
    index=[0, 1, 2])

In [28]:
#df1과 df3을 합치기, axis =1
df13_1=pd.concat([df1,df3], axis=1)
df13_1

A   B   C   D   E   F   G   H
0  A0  B0  C0  D0  A6  B6  C6  D6
1  A1  B1  C1  D1  A7  B7  C7  D7
2  A2  B2  C2  D2  A8  B8  C8  D8

In [31]:
df4 = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
     'B': ['B0', 'B1', 'B2'],
     'C': ['C0', 'C1', 'C2'],
     'E': ['E0', 'E1', 'E2']},
     index=[0, 1, 3])


In [33]:
pd.concat([df1,df4], axis= 1)

A    B    C    D    A    B    C    E
0   A0   B0   C0   D0   A0   B0   C0   E0
1   A1   B1   C1   D1   A1   B1   C1   E1
2   A2   B2   C2   D2  NaN  NaN  NaN  NaN
3  NaN  NaN  NaN  NaN   A2   B2   C2   E2

In [36]:
pd.concat([df1,df4], axis=0, join='outer')
#default: axis=0(열 기준, 위아래), join='outer'(합집합) 
#inner(교집합)



C:\Users\student\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


A   B   C    D    E
0  A0  B0  C0   D0  NaN
1  A1  B1  C1   D1  NaN
2  A2  B2  C2   D2  NaN
0  A0  B0  C0  NaN   E0
1  A1  B1  C1  NaN   E1
3  A2  B2  C2  NaN   E2

In [37]:
pd.concat([df1,df4], axis=0, join='inner')
#default: axis=0(열 기준, 위아래), join='outer'(합집합) 
#inner(교집합)
#axis =0, join='inner' 공통적인 열만 출력.
#'outer' - NaN 발생함. 어떻게 처리할지 생각해야 한다.




A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A0  B0  C0
1  A1  B1  C1
3  A2  B2  C2

In [40]:
df1
df4
pd.concat([df1,df4], axis=1, join='inner')

A   B   C   D   A   B   C   E
0  A0  B0  C0  D0  A0  B0  C0  E0
1  A1  B1  C1  D1  A1  B1  C1  E1

In [42]:
pd.concat([df1,df4], axis=1, join='inner', join_axes=[df1.index])
#df1과 df4를 좌우로 합친다. 
#행 인덱스가 공통적으로 존재하는 데이터에 대해 inner 교집합.
#join_axes로 인해 df1에 있는 모든 행 인덱스가 출력. 


C:\Users\student\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: The join_axes-keyword is deprecated. Use .reindex or .reindex_like on the result to achieve the same functionality.
  """Entry point for launching an IPython kernel.


A   B   C   D    A    B    C    E
0  A0  B0  C0  D0   A0   B0   C0   E0
1  A1  B1  C1  D1   A1   B1   C1   E1
2  A2  B2  C2  D2  NaN  NaN  NaN  NaN

In [43]:
df5 = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
     'B': ['B0', 'B1', 'B2'],
     'C': ['C0', 'C1', 'C2'],
     'D': ['D0', 'D1', 'D2']},
     index=['r0', 'r1', 'r2'])


df6 = pd.DataFrame({'A': ['A3', 'A4', 'A5'],
     'B': ['B3', 'B4', 'B5'],
     'C': ['C3', 'C4', 'C5'],
     'D': ['D3', 'D4', 'D5']},
     index=['r3', 'r4', 'r5'])

In [44]:
df5 #3건, 요소가 3개

A   B   C   D
r0  A0  B0  C0  D0
r1  A1  B1  C1  D1
r2  A2  B2  C2  D2

In [50]:
pd.concat([df5,df6],axis=0, ignore_index= True)
#데이터가 합쳐진후 ignore_index 행 인덱스가 다를 경우, 하나로 리셋팅을 해서 할때 사용.



A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5

In [54]:
pd.concat([df5,df6],axis=1, ignore_index= True)
#행 인덱스, 열 인덱스 모두 사용 가능, 이번엔 열 인덱스에 적용.
#A B C D 인게 0 1 2 3 4로 변경.


C:\Users\student\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


0    1    2    3    4    5    6    7
r0   A0   B0   C0   D0  NaN  NaN  NaN  NaN
r1   A1   B1   C1   D1  NaN  NaN  NaN  NaN
r2   A2   B2   C2   D2  NaN  NaN  NaN  NaN
r3  NaN  NaN  NaN  NaN   A3   B3   C3   D3
r4  NaN  NaN  NaN  NaN   A4   B4   C4   D4
r5  NaN  NaN  NaN  NaN   A5   B5   C5   D5

In [58]:
df56_keys=pd.concat([df5,df6],axis=0, keys=['df_5','df_6'])
#keys: 계층적으로 index를 생성 => 계층적으로 접근 가능
df56_keys


A   B   C   D
df_5 r0  A0  B0  C0  D0
     r1  A1  B1  C1  D1
     r2  A2  B2  C2  D2
df_6 r3  A3  B3  C3  D3
     r4  A4  B4  C4  D4
     r5  A5  B5  C5  D5

In [61]:
df56_keys.ix['df_5'] 
#ix 행 번호 기준으로 데이터를 검색할때 옵션
#계층적으로 접근 가능

C:\Users\student\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


A   B   C   D
r0  A0  B0  C0  D0
r1  A1  B1  C1  D1
r2  A2  B2  C2  D2

In [64]:
df56_keys.ix['df_5'][1:2] 
#ix 행 번호 기준으로 데이터를 검색할때 옵션
#계층적으로 접근 가능
#행 추출시 범위로 명시해야 더 안쪽까지 접근 가능


C:\Users\student\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


A   B   C   D
r1  A1  B1  C1  D1

In [65]:
df56_keys=pd.concat([df5,df6],axis=0, keys=['df_5','df_6'], names=['dfName', 'rowData'])
#keys: 계층적으로 index를 생성 => 계층적으로 접근 가능
df56_keys


A   B   C   D
dfName rowData                
df_5   r0       A0  B0  C0  D0
       r1       A1  B1  C1  D1
       r2       A2  B2  C2  D2
df_6   r3       A3  B3  C3  D3
       r4       A4  B4  C4  D4
       r5       A5  B5  C5  D5

In [67]:
import warnings
warnings.filterwarnings(action='ignore')

In [68]:
#verify_integrity:index 중복 여부 확인
#default:False
#True로 설정하게 되면, index 중복시 에러 발생



In [70]:
df7 = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
     'B': ['B0', 'B1', 'B2'],
     'C': ['C0', 'C1', 'C2'],
     'D': ['D0', 'D1', 'D2']},
     index=['r0', 'r1', 'r2'])

df8 = pd.DataFrame({'A': ['A2', 'A3', 'A4'],
     'B': ['B2', 'B3', 'B4'],
     'C': ['C2', 'C3', 'C4'],
     'D': ['D2', 'D3', 'D4']},
     index=['r2', 'r3', 'r4'])


In [71]:
df7

A   B   C   D
r0  A0  B0  C0  D0
r1  A1  B1  C1  D1
r2  A2  B2  C2  D2

In [72]:
df8

A   B   C   D
r2  A2  B2  C2  D2
r3  A3  B3  C3  D3
r4  A4  B4  C4  D4

In [75]:
pd.concat([df7,df8],verify_integrity=True)
#데이터가 중복이 있는지 없는지 확인하기 위한.
#해결방안, 인덱스명 바꾸거나, ignore index 하거나.


ValueError: Indexes have overlapping values: Index(['r2'], dtype='object')

In [77]:
#concat함수, append함수: 데이터프레임과 시리즈간 합치기 가능.
from pandas import DataFrame
from pandas import Series



In [78]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2'],
    'D': ['D0', 'D1', 'D2']},
    index=[0, 1, 2])

In [87]:
type(df1)
df1['A'] #df1.A
df1[['A','B']] #대괄호 2개해야 참조
type(df1[['A','B']])
#데이터 열 하나 하나를 Series라고 한다. 이러한 Series가 모이면 DataFrame이 된다.

pandas.core.frame.DataFrame

In [99]:
S1=pd.Series(['s1','s2','s3'],name='S')
S1


0    s1
1    s2
2    s3
Name: S, dtype: object

In [103]:
pd.concat([df1,S1], axis=1, ignore_index=True) #axis=1 좌우 합침. 행기준, 위에 열 index가 0 1 2 3 4로 바뀜.

0   1   2   3   4
0  A0  B0  C0  D0  s1
1  A1  B1  C1  D1  s2
2  A2  B2  C2  D2  s3

In [111]:
S1=pd.Series(['s1','s2','s3'],name='S')
S2=pd.Series([1,2,3])
S3=pd.Series([4,5,6])
pd.concat([S1,S2,S3],axis=1,ignore_index=True)


0  1  2
0  s1  1  4
1  s2  2  5
2  s3  3  6

In [112]:
type(pd.concat([S1,S2,S3],axis=1,ignore_index=True))
#열들이 모이면 DataFrame이 된다. 

pandas.core.frame.DataFrame

In [113]:
# merge:속도가 concat보다 빠름. SQL명령문과 비슷
help(pd.merge)
# merge(left, right, how='inner', on=None, left_on=None, right_on=None, 
# left_index=False, right_index=False, sort=False, suffixes=('_x', '_y'), 
#copy=True, indicator=False, validate=None)
#     Merge DataFrame or named Series objects with a database-style join.

Help on function merge in module pandas.core.reshape.merge:

merge(left, right, how='inner', on=None, left_on=None, right_on=None, left_index=False, right_index=False, sort=False, suffixes=('_x', '_y'), copy=True, indicator=False, validate=None)
    Merge DataFrame or named Series objects with a database-style join.
    
    The join is done on columns or indexes. If joining columns on
    columns, the DataFrame indexes *will be ignored*. Otherwise if joining indexes
    on indexes or indexes on a column or columns, the index will be passed on.
    
    Parameters
    ----------
    left : DataFrame
    right : DataFrame or named Series
        Object to merge with.
    how : {'left', 'right', 'outer', 'inner'}, default 'inner'
        Type of merge to be performed.
    
        * left: use only keys from left frame, similar to a SQL left outer join;
          preserve key order.
        * right: use only keys from right frame, similar to a SQL right outer join;
          preserve key 

In [114]:
dfleft = DataFrame({'KEY': ['K0', 'K1', 'K2', 'K3'],
    'A': ['A0', 'A1', 'A2', 'A3'],
    'B': ['B0', 'B1', 'B2', 'B3']})


dfright = DataFrame({'KEY': ['K2', 'K3', 'K4', 'K5'],
    'C': ['C2', 'C3', 'C4', 'C5'],
    'D': ['D2', 'D3', 'D4', 'D5']})

In [115]:
dfleft

KEY   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [116]:
dfright

KEY   C   D
0  K2  C2  D2
1  K3  C3  D3
2  K4  C4  D4
3  K5  C5  D5

In [119]:
# dfleft, dfright를 KEY변수를 기준으로 merge
pd.merge(dfleft,dfright, how='inner')


KEY   A   B   C   D
0  K2  A2  B2  C2  D2
1  K3  A3  B3  C3  D3

In [120]:
pd.merge(dfleft,dfright, how='outer')

KEY    A    B    C    D
0  K0   A0   B0  NaN  NaN
1  K1   A1   B1  NaN  NaN
2  K2   A2   B2   C2   D2
3  K3   A3   B3   C3   D3
4  K4  NaN  NaN   C4   D4
5  K5  NaN  NaN   C5   D5

In [ ]:
#KEY를 기준으로 나온다.

In [128]:
pd.merge(dfleft,dfright,
        how="left", on='KEY') 
#left꺼 다 나오고, right와 공통은 C2,3 D2,3이 나온다.
#on =' ' on을 기준으로 나뉜다.
#공통인 column을 on에 적어야 한다. 


KEY   A   B    C    D
0  K0  A0  B0  NaN  NaN
1  K1  A1  B1  NaN  NaN
2  K2  A2  B2   C2   D2
3  K3  A3  B3   C3   D3

In [127]:
pd.merge(dfleft,dfright,
        how="right", on='KEY') 
#right꺼 다 나온다. K0, K1은 안나온다. 

KEY    A    B   C   D
0  K2   A2   B2  C2  D2
1  K3   A3   B3  C3  D3
2  K4  NaN  NaN  C4  D4
3  K5  NaN  NaN  C5  D5

In [129]:
dfleft

KEY   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [130]:
dfright

KEY   C   D
0  K2  C2  D2
1  K3  C3  D3
2  K4  C4  D4
3  K5  C5  D5

In [138]:
pd.merge(dfleft,dfright, how='outer', on='KEY',indicator=True)
pd.merge(dfleft,dfright, how='outer', on='KEY',indicator='indicator_info()')

#default how='inner' 이다.교집합

KEY    A    B    C    D indicator_info()
0  K0   A0   B0  NaN  NaN        left_only
1  K1   A1   B1  NaN  NaN        left_only
2  K2   A2   B2   C2   D2             both
3  K3   A3   B3   C3   D3             both
4  K4  NaN  NaN   C4   D4       right_only
5  K5  NaN  NaN   C5   D5       right_only

In [142]:
dfleft2 = DataFrame({'KEY': ['K0', 'K1', 'K2', 'K3'],
     'A': ['A0', 'A1', 'A2', 'A3'],
     'B': ['B0', 'B1', 'B2', 'B3'],
     'C': ['C0', 'C1', 'C2', 'C3']})

dfright2 = DataFrame({'KEY': ['K0', 'K1', 'K2', 'K3'],
     'B': ['B0_2', 'B1_2', 'B2_2', 'B3_2'],
     'C': ['C0_2', 'C1_2', 'C2_2', 'C3_2'],
     'D': ['D0_2', 'D1_2', 'D2_2', 'D3_3']})


In [147]:
pd.merge(dfleft2,dfright2, how='inner', on='KEY', suffixes=('_left', '_right'))
#공통인게 여러 컬럼 있어서 자동으로 안되고 정해줘야 나온다. 



KEY   A B_left C_left B_right C_right     D
0  K0  A0     B0     C0    B0_2    C0_2  D0_2
1  K1  A1     B1     C1    B1_2    C1_2  D1_2
2  K2  A2     B2     C2    B2_2    C2_2  D2_2
3  K3  A3     B3     C3    B3_2    C3_2  D3_3

In [ ]:
#데이터프레임을 인덱스를 기준으로 병합

In [154]:
dfleft = DataFrame({
    'A': ['A0', 'A1', 'A2', 'A3'],
    'B': ['B0', 'B1', 'B2', 'B3']}, index=['K0', 'K1', 'K2', 'K3'])


dfright = DataFrame({
    'C': ['C2', 'C3', 'C4', 'C5'],
    'D': ['D2', 'D3', 'D4', 'D5']}, index=['K2', 'K3', 'K4', 'K5'])

In [155]:
dfleft

A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2
K3  A3  B3

In [156]:
dfright

C   D
K2  C2  D2
K3  C3  D3
K4  C4  D4
K5  C5  D5

In [160]:
#index 기준 병합 방법: join(), merge()
#index를 기준으로 left join 수행

#merge()를 이용한 left join
pd.merge(dfleft,dfright, left_index=True, right_index=True)# left, right 공통 부분 출력.
pd.merge(dfleft,dfright, left_index=True, right_index=True, how='right')
#how='left' 붙이면 left에 관한 요소 모두 출력. 왼쪽오른쪽 비교.

A    B   C   D
K2   A2   B2  C2  D2
K3   A3   B3  C3  D3
K4  NaN  NaN  C4  D4
K5  NaN  NaN  C5  D5

In [169]:
pd.merge(dfleft,dfright, left_index=True, right_index=True, how='right')
#how에 'left','right','inner','outer' 가능

dfleft.join(dfright) #pd.merge(dfleft,dfright, how='left')
#join함수는 DataFrame이 가지고 있고, merge함수는 pd, pandas가 가지고 있다.
dfleft.join(dfright, how='right')#default가 left, how로 설정.


A    B   C   D
K2   A2   B2  C2  D2
K3   A3   B3  C3  D3
K4  NaN  NaN  C4  D4
K5  NaN  NaN  C5  D5

In [170]:
dfleft = DataFrame({'KEY': ['K0', 'K1', 'K2', 'K3'],
    'A': ['A0', 'A1', 'A2', 'A3'],
    'B': ['B0', 'B1', 'B2', 'B3']})


dfright = DataFrame({'KEY': ['K2', 'K3', 'K4', 'K5'],
    'C': ['C2', 'C3', 'C4', 'C5'],
    'D': ['D2', 'D3', 'D4', 'D5']})

In [174]:
#index 기준 합치기,(merge함수 이용)
# K0
# K1
# K2
# K3
dfleft = DataFrame({
    'A': ['A0', 'A1', 'A2', 'A3'],
    'B': ['B0', 'B1', 'B2', 'B3']}, index=['K0', 'K1', 'K2', 'K3'])


dfright = DataFrame({
    'C': ['C2', 'C3', 'C4', 'C5'],
    'D': ['D2', 'D3', 'D4', 'D5']}, index=['K2', 'K3', 'K4', 'K5'])
pd.merge(dfleft,dfright, left_index=True, right_index=True, how='left')


A   B    C    D
K0  A0  B0  NaN  NaN
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2
K3  A3  B3   C3   D3

In [176]:
#join 함수를 이용하여 동일한 결과 출력

dfleft.join(dfright) #defaul: How='left'
# dfleft.join(dfright, how='left')

A   B    C    D
K0  A0  B0  NaN  NaN
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2
K3  A3  B3   C3   D3

In [177]:
dfright.join(dfleft)

C   D    A    B
K2  C2  D2   A2   B2
K3  C3  D3   A3   B3
K4  C4  D4  NaN  NaN
K5  C5  D5  NaN  NaN

In [181]:
#merge함수 이용
pd.merge(dfleft,dfright, left_index=True, right_index=True, how='outer')


A    B    C    D
K0   A0   B0  NaN  NaN
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3   A3   B3   C3   D3
K4  NaN  NaN   C4   D4
K5  NaN  NaN   C5   D5

In [183]:
#dfleft, dfright를 outer join
dfleft.join(dfright, how='outer')

A    B    C    D
K0   A0   B0  NaN  NaN
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3   A3   B3   C3   D3
K4  NaN  NaN   C4   D4
K5  NaN  NaN   C5   D5

In [188]:
#index와 key를 조합하여 merge
dfleft = DataFrame({'KEY':['K0', 'K1', 'K2', 'K3'],
    'A': ['A0', 'A1', 'A2', 'A3'],
    'B': ['B0', 'B1', 'B2', 'B3']})


dfright = DataFrame({
    'C': ['C2', 'C3', 'C4', 'C5'],
    'D': ['D2', 'D3', 'D4', 'D5']}, index=['K2', 'K3', 'K4', 'K5'])

#KEY 열과 index가 같은걸 합치려는 작업

dfleft
#dfright

KEY   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [194]:
#merge 함수로 표현
pd.merge(dfleft, dfright, left_on="KEY", right_index=True, how='left')


KEY   A   B    C    D
0  K0  A0  B0  NaN  NaN
1  K1  A1  B1  NaN  NaN
2  K2  A2  B2   C2   D2
3  K3  A3  B3   C3   D3

In [195]:
dfleft.join(dfright, on="KEY", how='left')

KEY   A   B    C    D
0  K0  A0  B0  NaN  NaN
1  K1  A1  B1  NaN  NaN
2  K2  A2  B2   C2   D2
3  K3  A3  B3   C3   D3

In [242]:
#문제 1 번.
pd.read_csv("C:/Users/student/Downloads/데이터병합 연습데이터.txt", sep="\n", header=None)
df12_merge=pd.merge(df1,df2, left_index=True, right_index=True, how='outer' )
df123=pd.merge(df12_merge,df3, left_index=True, right_index=True, how='outer')
df123

A_x  B_x  C_x  D_x  A_y  B_y  C_y  D_y    E    F    G    H
0   A0   B0   C0   D0  NaN  NaN  NaN  NaN   A6   B6   C6   D6
1   A1   B1   C1   D1  NaN  NaN  NaN  NaN   A7   B7   C7   D7
2   A2   B2   C2   D2  NaN  NaN  NaN  NaN   A8   B8   C8   D8
3  NaN  NaN  NaN  NaN   A3   B3   C3   D3  NaN  NaN  NaN  NaN
4  NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5  NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN

In [234]:
#문제 2번 how 변경
pd.read_csv("C:/Users/student/Downloads/데이터병합 연습데이터.txt", sep="\n", header=None)
df12=pd.merge(df1,df2,left_index=True, right_index=True, how='inner', suffixes=('_1', '_2'))
df123=pd.merge(df12,df3,left_index=True, right_index=True, how='outer')
df123

A_1  B_1  C_1  D_1  A_2  B_2  C_2  D_2   E   F   G   H
0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A6  B6  C6  D6
1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A7  B7  C7  D7
2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A8  B8  C8  D8

In [235]:
#문제 2번 how 변경
pd.read_csv("C:/Users/student/Downloads/데이터병합 연습데이터.txt", sep="\n", header=None)
df12=pd.merge(df1,df2,left_index=True, right_index=True, how='outer', suffixes=('_1', '_2'))
#df12
df123=pd.merge(df12,df3,left_index=True, right_index=True, how='outer')
df123


A_1  B_1  C_1  D_1  A_2  B_2  C_2  D_2    E    F    G    H
0   A0   B0   C0   D0  NaN  NaN  NaN  NaN   A6   B6   C6   D6
1   A1   B1   C1   D1  NaN  NaN  NaN  NaN   A7   B7   C7   D7
2   A2   B2   C2   D2  NaN  NaN  NaN  NaN   A8   B8   C8   D8
3  NaN  NaN  NaN  NaN   A3   B3   C3   D3  NaN  NaN  NaN  NaN
4  NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5  NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN

In [240]:
#문제 2번 axis 안됨
pd.read_csv("C:/Users/student/Downloads/데이터병합 연습데이터.txt", sep="\n", header=None)
df12_1=pd.merge(df1,df2,left_index=True, right_index=True, how='outer', axis=0)
df12_1

TypeError: merge() got an unexpected keyword argument 'axis'

In [241]:
#문제 2번 how 변경
pd.read_csv("C:/Users/student/Downloads/데이터병합 연습데이터.txt", sep="\n", header=None)
df12=pd.merge(df1,df2,left_index=True, right_index=True, how='outer', suffixes=('_1', '_2'))
#df12
df123=pd.merge(df12,df3,left_index=True, right_index=True, how='inner' )
df123


A_1 B_1 C_1 D_1  A_2  B_2  C_2  D_2   E   F   G   H
0  A0  B0  C0  D0  NaN  NaN  NaN  NaN  A6  B6  C6  D6
1  A1  B1  C1  D1  NaN  NaN  NaN  NaN  A7  B7  C7  D7
2  A2  B2  C2  D2  NaN  NaN  NaN  NaN  A8  B8  C8  D8

In [252]:
#문제 1번. concat사용해서 위아래 합침. 
pd.read_csv("C:/Users/student/Downloads/데이터병합 연습데이터.txt", sep="\n", header=None)
df123=pd.concat([df1,df2,df3], axis=0, keys=['df_1','df_2','df_3'], names= ['dfName','rowData'])
df123


A    B    C    D    E    F    G    H
dfName rowData                                        
df_1   0         A0   B0   C0   D0  NaN  NaN  NaN  NaN
       1         A1   B1   C1   D1  NaN  NaN  NaN  NaN
       2         A2   B2   C2   D2  NaN  NaN  NaN  NaN
df_2   3         A3   B3   C3   D3  NaN  NaN  NaN  NaN
       4         A4   B4   C4   D4  NaN  NaN  NaN  NaN
       5         A5   B5   C5   D5  NaN  NaN  NaN  NaN
df_3   0        NaN  NaN  NaN  NaN   A6   B6   C6   D6
       1        NaN  NaN  NaN  NaN   A7   B7   C7   D7
       2        NaN  NaN  NaN  NaN   A8   B8   C8   D8

In [256]:
pd.read_csv("C:/Users/student/Downloads/데이터병합 연습데이터.txt", sep="\n", header=None)
df123=pd.concat([df1,df2,df3], axis=0, keys=['df_1','df_2','df_3'], names= ['dfName','rowData'], join='inner')
df123


Empty DataFrame
Columns: []
Index: [(df_1, 0), (df_1, 1), (df_1, 2), (df_2, 3), (df_2, 4), (df_2, 5), (df_3, 0), (df_3, 1), (df_3, 2)]

In [257]:
pd.read_csv("C:/Users/student/Downloads/데이터병합 연습데이터.txt", sep="\n", header=None)
df123=pd.concat([df1,df2,df3], axis=0, keys=['df_1','df_2','df_3'], names= ['dfName','rowData'], join='outer')
df123


A    B    C    D    E    F    G    H
dfName rowData                                        
df_1   0         A0   B0   C0   D0  NaN  NaN  NaN  NaN
       1         A1   B1   C1   D1  NaN  NaN  NaN  NaN
       2         A2   B2   C2   D2  NaN  NaN  NaN  NaN
df_2   3         A3   B3   C3   D3  NaN  NaN  NaN  NaN
       4         A4   B4   C4   D4  NaN  NaN  NaN  NaN
       5         A5   B5   C5   D5  NaN  NaN  NaN  NaN
df_3   0        NaN  NaN  NaN  NaN   A6   B6   C6   D6
       1        NaN  NaN  NaN  NaN   A7   B7   C7   D7
       2        NaN  NaN  NaN  NaN   A8   B8   C8   D8

In [245]:
#문제 2번.
pd.read_csv("C:/Users/student/Downloads/데이터병합 연습데이터.txt", sep="\n", header=None)
pd.concat([df1,df2,df3], axis=1)

A    B    C    D    A    B    C    D    E    F    G    H
0   A0   B0   C0   D0  NaN  NaN  NaN  NaN   A6   B6   C6   D6
1   A1   B1   C1   D1  NaN  NaN  NaN  NaN   A7   B7   C7   D7
2   A2   B2   C2   D2  NaN  NaN  NaN  NaN   A8   B8   C8   D8
3  NaN  NaN  NaN  NaN   A3   B3   C3   D3  NaN  NaN  NaN  NaN
4  NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5  NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN

In [253]:
pd.read_csv("C:/Users/student/Downloads/데이터병합 연습데이터.txt", sep="\n", header=None)
pd.concat([df1,df2,df3], axis=1, join='inner')

Empty DataFrame
Columns: [A, B, C, D, A, B, C, D, E, F, G, H]
Index: []

In [255]:
pd.read_csv("C:/Users/student/Downloads/데이터병합 연습데이터.txt", sep="\n", header=None)
pd.concat([df1,df2,df3], axis=1, join='outer')

A    B    C    D    A    B    C    D    E    F    G    H
0   A0   B0   C0   D0  NaN  NaN  NaN  NaN   A6   B6   C6   D6
1   A1   B1   C1   D1  NaN  NaN  NaN  NaN   A7   B7   C7   D7
2   A2   B2   C2   D2  NaN  NaN  NaN  NaN   A8   B8   C8   D8
3  NaN  NaN  NaN  NaN   A3   B3   C3   D3  NaN  NaN  NaN  NaN
4  NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5  NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN

In [264]:
pd.read_csv("C:/Users/student/Downloads/데이터병합 연습데이터.txt", sep="\n", header=None)
pd.concat([df1,df2,df3], axis=0, join='outer',ignore_index=True)


A    B    C    D    E    F    G    H
0   A0   B0   C0   D0  NaN  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN  NaN
2   A2   B2   C2   D2  NaN  NaN  NaN  NaN
3   A3   B3   C3   D3  NaN  NaN  NaN  NaN
4   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6  NaN  NaN  NaN  NaN   A6   B6   C6   D6
7  NaN  NaN  NaN  NaN   A7   B7   C7   D7
8  NaN  NaN  NaN  NaN   A8   B8   C8   D8

In [274]:
pd.read_csv("C:/Users/student/Downloads/데이터병합 연습데이터.txt", sep="\n", header=None)
df12_merge=pd.merge(df1,df2, left_index=True, right_index=True, how='outer' )
df12_merge.join(df3, how='left')
#df123=pd.merge(df12_merge,df3, left_index=True, right_index=True, how='outer')



# pd.read_csv("C:/Users/student/Downloads/데이터병합 연습데이터.txt", sep="\n", header=None)
#pd.merge(dfleft,dfright, left_index=True, right_index=True, how='outer')
# dfleft.join(dfright, on="KEY", how='left')

A_x  B_x  C_x  D_x  A_y  B_y  C_y  D_y    E    F    G    H
0   A0   B0   C0   D0  NaN  NaN  NaN  NaN   A6   B6   C6   D6
1   A1   B1   C1   D1  NaN  NaN  NaN  NaN   A7   B7   C7   D7
2   A2   B2   C2   D2  NaN  NaN  NaN  NaN   A8   B8   C8   D8
3  NaN  NaN  NaN  NaN   A3   B3   C3   D3  NaN  NaN  NaN  NaN
4  NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5  NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN

In [275]:
pd.read_csv("C:/Users/student/Downloads/데이터병합 연습데이터.txt", sep="\n", header=None)
df12_merge=pd.merge(df1,df2, left_index=True, right_index=True, how='outer' )
df12_merge.join(df3, how='right')

A_x B_x C_x D_x  A_y  B_y  C_y  D_y   E   F   G   H
0  A0  B0  C0  D0  NaN  NaN  NaN  NaN  A6  B6  C6  D6
1  A1  B1  C1  D1  NaN  NaN  NaN  NaN  A7  B7  C7  D7
2  A2  B2  C2  D2  NaN  NaN  NaN  NaN  A8  B8  C8  D8

In [287]:
pd.read_csv("C:/Users/student/Downloads/데이터병합 연습데이터.txt", sep="\n", header=None)
df12_merge=pd.merge(df1,df2, left_index=True, right_index=True, how='outer' )
df123=df12_merge.join(df3, how='left')
df123
df123.to_csv("df123.csv", header=None)

In [300]:
#문제 5번.servey_ 파일에 대해 merge 연습
df_visited=pd.read_csv("C:/Users/student/Downloads/data/survey_visited.csv")
df_visited
df_site=pd.read_csv("C:/Users/student/Downloads/data/survey_site.csv")
df_site
#pd.merge(df)
pd.merge(df_visited,df_site, left_on='site', right_on='name')
#pd.merge(dfleft, dfright, left_on="KEY", right_index=True, how='left')

ident   site       dated   name    lat    long
0    619   DR-1  1927-02-08   DR-1 -49.85 -128.57
1    622   DR-1  1927-02-10   DR-1 -49.85 -128.57
2    844   DR-1  1932-03-22   DR-1 -49.85 -128.57
3    734   DR-3  1939-01-07   DR-3 -47.15 -126.72
4    735   DR-3  1930-01-12   DR-3 -47.15 -126.72
5    751   DR-3  1930-02-26   DR-3 -47.15 -126.72
6    752   DR-3         NaN   DR-3 -47.15 -126.72
7    837  MSK-4  1932-01-14  MSK-4 -48.87 -123.40

In [290]:
pd.read_csv("C:/Users/student/Downloads/data/survey_site.csv")

name    lat    long
0   DR-1 -49.85 -128.57
1   DR-3 -47.15 -126.72
2  MSK-4 -48.87 -123.40

In [302]:
#문제 6. 빌딩 좌우 공백 2칸, 조망권
import numpy as np
Building=[0,0,3,5,2,4,8,0,6,4,0,6,0,0]
array=arr.


In [19]:
#문제 1번
from pandas import DataFrame
import pandas as pd
df1=pd.read_csv("C:/Users/student/Downloads/data/concat_1.csv")
df2=pd.read_csv("C:/Users/student/Downloads/data/concat_2.csv")
df3=pd.read_csv("C:/Users/student/Downloads/data/concat_3.csv")
#df123_merge=pd.concat([df1,df2,df3],axis=0, keys=['df_1','df_2','df_3'], names= ['dfName','rowData'],ignore_index= True )

#df123_merge=pd.concat([df1,df2,df3],axis=0, keys=['df_1','df_2','df_3'], names= ['dfName','rowData'],ignore_index= True )

#df123_merge=pd.concat([df1,df2,df3], axis=0, join='outer',ignore_index=True)

#df123_merge
df12_merge=pd.merge(df1,df2, left_index=True, right_index=True, how='outer' )
df12_merge.join(df3, how='left')

A_x B_x C_x D_x A_y B_y C_y D_y    A    B    C    D
0  a0  b0  c0  d0  a4  b4  c4  d4   a8   b8   c8   d8
1  a1  b1  c1  d1  a5  b5  c5  d5   a9   b9   c9   d9
2  a2  b2  c2  d2  a6  b6  c6  d6  a10  b10  c10  d10
3  a3  b3  c3  d3  a7  b7  c7  d7  a11  b11  c11  d11

In [17]:
import numpy as np
height=[0,0,3,5,2,4,9,0,6,4,0,6,0,0]
num=[-2,-1,1,2] # 2이상의 공간이 확보 되어있는 판단하기 위한 리스트
zero=np.zeros((15,15)) # 15x15 영행렬 생성
cnt=0
for i in height:
    if i !=0:
        zero[:14-i:-1,cnt]=1 # 영행렬에서 리스트 만큼의 높이의 빌딩 층수를 1로 찍어 줌 // 빌딩의 층 = 1
    cnt+=1
print(zero,"\n\n")    

dump=0
cnt=0

for i in range(15):
    for j in range(15):
        if zero[i][j]==1: # 행렬에서 1을 만나면
            cnt=0
            for k in num:
                if zero[i][j-k]==0:  # 1의 좌우 2칸이 전부 0인지 판단
                    cnt+=1
                if cnt==4:
                    dump+=1
# print(cnt)
print(dump)    

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 1. 1. 0. 1. 1. 0. 1. 0. 0. 0.]
 [0. 0. 1. 1. 0. 1. 1. 0. 1. 1. 0. 1. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 1. 1. 0. 1. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 1. 1. 0. 1. 0. 0. 0.]] 


6


In [18]:
import numpy as np
inputData=[0,0,3,5,2,4,9,0,6,4,0,6,0,0]
buildData=[[0]*14]*10
buildData=np.array(buildData)
count=0
for i in range (0,14):#그저 보기 편하게
    for j in range(0,inputData[i]):
        buildData[9-j][i]=1
print(buildData)
for i in range(2,12):#가장 높은 층만 찾아서 조망권 검사
    j=0
    while True:
        print(i,inputData[i]-j,inputData[i-1],inputData[i-2],inputData[i+1],inputData[i+2])
        if (inputData[i]-j) > (inputData[i-1]) and (inputData[i]-j) > (inputData[i-2]) and (inputData[i]-j) > (inputData[i+1]) and (inputData[i]-j) > (inputData[i+2]):
            count+=1
            j+=1
        else:
            break
print(count)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 1 0 0 1 0 0]
 [0 0 0 1 0 0 1 0 1 0 0 1 0 0]
 [0 0 0 1 0 1 1 0 1 1 0 1 0 0]
 [0 0 1 1 0 1 1 0 1 1 0 1 0 0]
 [0 0 1 1 1 1 1 0 1 1 0 1 0 0]
 [0 0 1 1 1 1 1 0 1 1 0 1 0 0]]
2 3 0 0 5 2
3 5 3 0 2 4
3 4 3 0 2 4
4 2 5 3 4 9
5 4 2 5 9 0
6 9 4 2 0 6
6 8 4 2 0 6
6 7 4 2 0 6
6 6 4 2 0 6
7 0 9 4 6 4
8 6 0 9 4 0
9 4 6 0 0 6
10 0 4 6 6 0
11 6 0 4 0 0
11 5 0 4 0 0
11 4 0 4 0 0
6


In [20]:
# 예시 {0,0,3,5,2,4,8,0,6,4,0,6,0,0} 상황일때 조망권이 확보된 세대는 6
res=[]
num=[]
sample = [0,0,3,5,2,4,9,0,6,4,0,6,0,0]
for i in range(2,len(sample)-2):
    if sample[i]>sample[i-2] and sample[i]>sample[i-1] and sample[i]>sample[i+1] and sample[i]>sample[i+2]:
        res.append(i)
        num.append(sample[i]-max([sample[i-2],sample[i-1],sample[i+1],sample[i+2]]))

for i in range(len(res)):
    print("{}번째 빌딩에 {}세대".format(res[i],num[i]))
print("조망권이 보장된 세대는 총 %d세대입니다"%sum(num))


3번째 빌딩에 1세대
6번째 빌딩에 3세대
11번째 빌딩에 2세대
조망권이 보장된 세대는 총 6세대입니다


In [ ]:
#문제 1번~4번
from pandas import DataFrame
import pandas as pd
df1=pd.read_csv("C:/Users/student/Downloads/data/concat_1.csv")
df2=pd.read_csv("C:/Users/student/Downloads/data/concat_2.csv")
df3=pd.read_csv("C:/Users/student/Downloads/data/concat_3.csv")
df123_merge=pd.concat([df1,df2,df3],axis=0, keys=['df_1','df_2','df_3'], names= ['dfName','rowData'],ignore_index= True )

#df123_merge=pd.concat([df1,df2,df3],axis=0, keys=['df_1','df_2','df_3'], names= ['dfName','rowData'],ignore_index= True )

df123_merge=pd.concat([df1,df2,df3], axis=0, join='outer',ignore_index=True)

df123_merge

#join
df12_merge=pd.merge(df1,df2, left_index=True, right_index=True, how='outer' )
df12_merge.join(df3, how='left')


#문제 5번.servey_ 파일에 대해 merge 연습
df_visited=pd.read_csv("C:/Users/student/Downloads/data/survey_visited.csv")
df_visited
df_site=pd.read_csv("C:/Users/student/Downloads/data/survey_site.csv")
df_site
#pd.merge(df)
pd.merge(df_visited,df_site, left_on='site', right_on='name')
#pd.merge(dfleft, dfright, left_on="KEY", right_index=True, how='left')

