In [1]:
#배열 축 추가:np.newaxis, np.tile
import numpy as np



In [2]:
a=np.array([1,2,3,4])
a
a.shape #(4,)

(4,)

In [3]:
a41=a[:,np.newaxis] #(4, 1)
a41 #4행 1열로 만든다.
a41.shape

(4, 1)

In [4]:
a41=a[np.newaxis,:]#(1, 4)
a41.shape 

(1, 4)

In [5]:
b=np.arange(15).reshape(3,5)
b
b351=b[:, :, np.newaxis]
b351
b351.shape #(3, 5, 1)
b351=b[:, np.newaxis,:]
b351
#b351.shape #(3, 1, 5)

array([[[ 0,  1,  2,  3,  4]],

       [[ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14]]])

In [6]:
a=np.array([0,1,2,3])
a8=np.tile(a,2) #array([0, 1, 2, 3, 0, 1, 2, 3])
a8

a32=np.tile(a,(3,2))
a32
# array([[0, 1, 2, 3, 0, 1, 2, 3],
#        [0, 1, 2, 3, 0, 1, 2, 3],
#        [0, 1, 2, 3, 0, 1, 2, 3]])

b=np.arange(8).reshape(2,4)
b
# array([[0, 1, 2, 3],
#        [4, 5, 6, 7]])
b28=np.tile(b,2)
b28
# array([[0, 1, 2, 3, 0, 1, 2, 3],
#        [4, 5, 6, 7, 4, 5, 6, 7]])

b44=np.tile(b,(2,1))
b44
# array([[0, 1, 2, 3],
#        [4, 5, 6, 7],
#        [0, 1, 2, 3],
#        [4, 5, 6, 7]])

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [0, 1, 2, 3],
       [4, 5, 6, 7]])

In [7]:
#행렬의 내적: aT * a : (전치 행렬) * (원래 행렬)
a=np.arange(15).reshape(3,5)
a
# array([[ 0,  1,  2,  3,  4],
#        [ 5,  6,  7,  8,  9],
#        [10, 11, 12, 13, 14]])

a.T
# array([[ 0,  5, 10],
#        [ 1,  6, 11],
#        [ 2,  7, 12],
#        [ 3,  8, 13],
#        [ 4,  9, 14]])

np.transpose(a)
# array([[ 0,  5, 10],
#        [ 1,  6, 11],
#        [ 2,  7, 12],
#        [ 3,  8, 13],
#        [ 4,  9, 14]])

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [8]:
a=np.arange(10)
a #array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
ai=a[0:5] ##array([0, 1, 2, 3, 4])
ai[1:3]=10
ai #array([ 0, 10, 10,  3,  4])
# a #함께 바뀐다. 어제 배웠던 부분(참조) #array([ 0, 10, 10,  3,  4,  5,  6,  7,  8,  9])


array([ 0, 10, 10,  3,  4])

In [9]:
arr=np.arange(20).reshape(5,4)
arr
# array([[ 0,  1,  2,  3],
#        [ 4,  5,  6,  7],
#        [ 8,  9, 10, 11],
#        [12, 13, 14, 15],
#        [16, 17, 18, 19]])
abc=np.array(['a','a','b','c','c'])


In [10]:
abc=='a' #array([ True,  True, False, False, False])
arr[abc=='a']
# array([[0, 1, 2, 3],
#        [4, 5, 6, 7]])
arr[abc=='a',:]
# array([[0, 1, 2, 3],
#        [4, 5, 6, 7]])
arr[abc=='a',:2]
# array([[0, 1],
#        [4, 5]])
arr[abc=='a',2] #array([2, 6])

arr[abc !='a']
# array([[ 8,  9, 10, 11],
#        [12, 13, 14, 15],
#        [16, 17, 18, 19]])
arr[~(abc =='a')]
# array([[ 8,  9, 10, 11],
#        [12, 13, 14, 15],
#        [16, 17, 18, 19]])
arr[(abc=='a') |(abc=='b')] #True,True,True,Flase,Flase
# array([[ 0,  1,  2,  3],
#        [ 4,  5,  6,  7],
#        [ 8,  9, 10, 11]])
arr[(abc!='a') &(abc!='b')] #c에 해당하는것
# array([[12, 13, 14, 15],
#        [16, 17, 18, 19]])
# arr[(abc!='a') and (abc!='b')] #value Error
# arr[(abc!='a') or (abc!='b')] #value Error

# arr에서 abc배열을 이용하여 'a'와 같은 행은 모두 99로 변경(불린 참조)
abc=="a" #array([ True,  True, False, False, False])
arr[(abc)=='a']=99
# array([[99, 99, 99, 99],
#        [99, 99, 99, 99]])
arr

array([[99, 99, 99, 99],
       [99, 99, 99, 99],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [11]:
#arr배열에서 20보다 큰 값은 모두 0으로 변경(불린 참조 사용, if or for문 사용 금지)
arr>20
arr[arr>20]=0
arr


array([[ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [12]:
#arr배열에서 8이상 15이하 값은 모두 10으로 변경(불린 참조 사용, if or for문 사용 금지)
(arr>= 8) & (arr<=15)
# array([[False, False, False, False],
#        [False, False, False, False],
#        [ True,  True,  True,  True],
#        [ True,  True,  True,  True],
#        [False, False, False, False]])
arr[(arr>= 8) & (arr<=15)]=10
arr

array([[ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [16, 17, 18, 19]])

In [13]:
#arr[8<=arr <=15] Value Error 문법오류
#arr[8<=arr & arr <=15] #Value Error  괄호 없어서 연산자 우선순위 오류.


In [14]:
#numpy에서 복소수 사용 가능

a=np.array([-3.5,-2.2,0,1.6,3.14,4.05])
np.around(a) #0.5 기준 내림 혹은 올림
np.round_(a,1) #소수이하 첫째자리까지 출력
np.rint(a) #가까운 정수로 올림 또는 내림
np.fix(a) # 0 방향으로 가까운 정수로 올림 또는 내림
np.ceil(a) #해당값보다 크거나 같은 가장 작은 정수로 올림.
np.floor(a)#r해당값보다 작거나 같은 경우 가장 큰 정수값으로 내림 
np.trunc(a) #소수 이하 버림




array([-3., -2.,  0.,  1.,  3.,  4.])

In [15]:
a=np.array([1,2,3,4])
c=np.arange(1,5).reshape(2,2)
c

array([[1, 2],
       [3, 4]])

In [16]:
#배열 요소값 곱셈
np.prod(c) #24
np.prod(c, axis=0) #array([3, 8]) # 열기준 곱셈
np.prod(c, axis=1) #array([ 2, 12]) #행기준 곱셈


array([ 2, 12])

In [17]:
np.sum(a) #10 #스칼라 #0차원
a # array([1, 2, 3, 4])
np.sum(a, keepdims=True) #array([10])
np.sum(c, axis=0) #array([4, 6])
np.sum(c, axis=1) #array([3, 7])

array([3, 7])

In [18]:
d=np.array([[1,2], [3,np.nan]])
d
# array([[ 1.,  2.],
#        [ 3., nan]])
np.prod(d) #nan
np.prod(d, axis=0) #array([ 3., nan])
np.prod(d, axis=1) #array([ 2., nan])

#np.nanprod:곱셈할때 nan을 '1'로 간주해서 곱셈.
np.nanprod(d, axis=0) #array([3., 2.])
np.nanprod(d, axis=1) #array([2., 3.])

array([2., 3.])

In [19]:
#np.nansum:덧셈할때 nan을 '0'으로 간주해서 곱셈.
d
np.sum(d) #nan
np.nansum(d) #6.0 #nan은 0으로 취급.

6.0

In [20]:
a #array([1, 2, 3, 4])
b=np.arange(1,7).reshape(2,3)
b
# array([[1, 2, 3],
#        [4, 5, 6]])

#np.cumprod: 누적 곱
np.cumprod(a) #array([ 1,  2,  6, 24], dtype=int32)
np.cumprod(b)  #array([  1,   2,   6,  24, 120, 720], dtype=int32)
np.cumprod(b, axis=0) #열
# array([[ 1,  2,  3],
#        [ 4, 10, 18]], dtype=int32)

#np.cumsum: 누적 합


array([[ 1,  2,  3],
       [ 4, 10, 18]], dtype=int32)

In [21]:
#지수함수, 로그함수

# 자연상수 e, y=logx or y=ln(x)

# 지수함수: np.exp(), 밑이 자연상수 e인 지수 함수로 변환.
x=np.array([0.00001, 1, 2, 10])
np.exp(x)
#array([1.00001000e+00, 2.71828183e+00, 7.38905610e+00, 2.20264658e+04])

np.log(x) 
#array([-11.51292546,   0.        ,   0.69314718,   2.30258509])

np.log2(x)
# array([-16.60964047,   0.        ,   1.        ,   3.32192809])

array([-16.60964047,   0.        ,   1.        ,   3.32192809])

In [22]:
#문제 1번. 데이터프레임 생성
import pandas as pd
df_score2=pd.DataFrame({'반': ['A','A','A','A','A',"B","B","B","B","B"],
      '번호':[1,2,3,4,5,1,2,3,4,5],
      '국어':[90,80,90,70,100,80,90,100,70,80],
      '영어':[100,90,100,80,70,90,100,70,80,90],
      '수학':[80,100,80,90,80,100,70,80,90,100]})
df_score2

반  번호   국어   영어   수학
0  A   1   90  100   80
1  A   2   80   90  100
2  A   3   90  100   80
3  A   4   70   80   90
4  A   5  100   70   80
5  B   1   80   90  100
6  B   2   90  100   70
7  B   3  100   70   80
8  B   4   70   80   90
9  B   5   80   90  100

In [23]:
#문제 2번. 1차 행 인덱스 '반', 2차 행 인덱스 '번호'
df_score3=df_score2.pivot_table(index=['반','번호'])
df_score3

국어   수학   영어
반 번호               
A 1    90   80  100
  2    80  100   90
  3    90   80  100
  4    70   90   80
  5   100   80   70
B 1    80  100   90
  2    90   70  100
  3   100   80   70
  4    70   90   80
  5    80  100   90

In [24]:
#문제 3번. 각 학생의 평균행 오른쪽에 추가

#각 학생들의 합(행기준)
df_score2.sum(axis=1)

# 반  번호
# A  1     270
#    2     270
#    3     270
#    4     240
#    5     250
# B  1     270
#    2     260
#    3     250
#    4     240
#    5     270
# dtype: int64

#평균열 추가(행기준)
df_score2.mean(axis=1)

df_score2['평균']=df_score2.mean(axis=1)
df_score2
# 반  번호
# A  1     90.000000
#    2     90.000000
#    3     90.000000
#    4     80.000000
#    5     83.333333
# B  1     90.000000
#    2     86.666667
#    3     83.333333
#    4     80.000000
#    5     90.000000

반  번호   국어   영어   수학     평균
0  A   1   90  100   80  67.75
1  A   2   80   90  100  68.00
2  A   3   90  100   80  68.25
3  A   4   70   80   90  61.00
4  A   5  100   70   80  63.75
5  B   1   80   90  100  67.75
6  B   2   90  100   70  65.50
7  B   3  100   70   80  63.25
8  B   4   70   80   90  61.00
9  B   5   80   90  100  68.75

In [25]:
#문제 4번. 행 인덱스를 "번호", 1차 열 인덱스 "국어", "영어", "수학". 2차 열 인덱스 "반"

df_score4=df_score3.pivot_table(index='번호', columns='반')
df_score4

# df1 = pd.pivot_table(df_score2,values=['국어','영어','수학'],index=['반','번호'])df1

국어        수학        영어     
반     A    B    A    B    A    B
번호                              
1    90   80   80  100  100   90
2    80   90  100   70   90  100
3    90  100   80   80  100   70
4    70   70   90   90   80   80
5   100   80   80  100   70   90

In [26]:
#문제 5. 각 반별 각 과목의 평균을 나타내는 행을 아래에 추가
# df_score3['평균']=
df_score4.loc['평균']=df_score4.mean(axis=0)
df_score4
#pd.merge(df_score3,mean_score3,how='outer')


국어            수학            영어       
반       A      B      A      B      A      B
번호                                          
1    90.0   80.0   80.0  100.0  100.0   90.0
2    80.0   90.0  100.0   70.0   90.0  100.0
3    90.0  100.0   80.0   80.0  100.0   70.0
4    70.0   70.0   90.0   90.0   80.0   80.0
5   100.0   80.0   80.0  100.0   70.0   90.0
평균   86.0   84.0   86.0   88.0   88.0   86.0

In [27]:
#문제 6번.
#양의 정수 I가 주어지면, 당신이 할 일은 I보다 큰 수 중 가장 작은 수 J를 찾습니다. 
# I의 이진수 형태에서의 1의 개수와 J의 이진수 형태에서의 1의 개수는 일치합니다.

def binary(data):
    

SyntaxError: unexpected EOF while parsing (<ipython-input-27-f0cafd822096>, line 6)

In [ ]:
while 1 :
    i = int(input())
    if i == 0 : break
        
    i_2 = format(i, 'b') # 이진수 형식으로 표현
    for j in range(i+1, 3*i) :
        j_2 = format(j, 'b')
        if j_2.count("1") == i_2.count("1") :
            res = j
            break
    print(res)


In [28]:
n = 78
n_over = n
binary = ""
while n >= 1:  # 이진수 만드는 부분
    binary = str(n % 2) + binary
    n //= 2
numOne = binary.count('1') # 이진수 값에서 1 갯수 세기
numOneX = 0
while numOne != numOneX: # 이진수 값이 같을 때 까지 1 씩 더하면서 숫자 찾아나감
    n_over += 1
    n = n_over
    checker = ""
    while n >= 1:
        checker = str(n % 2) + checker
        n //= 2
    numOneX = checker.count('1')
print(n_over)


83


In [ ]:
while True:
    ipt=input('정수를 입력하세요 : ')
    if ipt=='0':
        break
        
    # 입력한 정수 -> 이진수 -> 1 개수 세기
    cnt1=bin(int(ipt)).count('1')
    res=0
    # 1씩 더해가며 이진수로 변환했을 때 1 개수 세기
    while res!=cnt1:
        ipt=str(int(ipt)+1)
        res=bin(int(ipt)).count('1')
    
    print(ipt)
    
