In [ ]:
#오늘부터 Numpy(전처리), Pandas(분석) 병행 => 데이터 분석
#이전 시간 웹에서 스크랩핑, 이젠 DB에서 수집.
#신경망 공부해야한다. word2vec, 
"""
*전처리: 결측치(데이터 누락- 입력자의 실수, 수집이 잘 안된경우), 표준화/정규화 
- 어떻게 처리할지 기준이 필요(평균으로 할지, )
e.g., 한학생 국어 점수 누락- 반평균, 학교 평균, 전국 평균, 
비슷한 학생들의 평균, 이전 국어 점수들의 평균 

*다른쪽으로 대체 하는쪽으로 생각하는게 중요하다.
나름대로 잘 정의를 해야한다. 
=> KNN or 회구 분석으로 대체 하는 경우가 많다.

* 정규화: 분자: (각 속성값) - (최소)/분모:속성의 값 (최대) - (최소)
=> 0 ~ 1 사이로 표현. 임계치 설정해서 분류를 할 수 있다.
e.g., 각 국어점수 - 최소/국어점수의 최대-최소

* 표준화: 평균; 0, 표준편차; 1 
각 국어점수 - 평균 / 국어점수 표준편차

* 원핫 인코딩(One-hot Incoding): 현실의 추상적인 것을 이진화. 하나만 1로 나타내서 코딩
- 100000, 0100000, 0001000, ...  
    A        B        C
- "분류"를 해야하는 경우.(추상화 시킨것을 코딩에 매칭)
문장 추출 -> 단어(5개) 추출 -> 원핫인코딩 -> 5차원
e.g., 국어; 10000 영어; 01000 수학; 00100 과학; 00010 윤리;000001 -> 5차원


컴퓨터가 각각의 해당하는 것을 구분할수 있도록 하는것
사이즈가 작은 경우에는 경제적이고 효율적이다. 연산시에도 좋음.
단점: 사이즈가 큰 경우 메모리의 공간이 너무 많이 차지함.(10만개 같은 경우)
경제적이지 못하고 효율적이지 못하다.(비경제, 비효율) 

* 밀집벡터
문장 추출 -> 단어(5개) 추출 -> 밀집벡터(0 ~ 1의 값으로 표현), Word2Vec 알고리즘
훨씬 경제적이다. 차원(2차원 표현)수가 적어서 효율적이다.
국어[0.2, 0.7]
수학[0.1, 0.3]
단점: 차원이 줄어들면서 축의 의미가 애매해진다.(축은 데이터의 특성, 일반화의 특성을 나타내는데  
"""


In [ ]:
#numpy - 추치 연산에 전문화된 프로그램
#matplotlib, seaborn 시각화, 
"""
1. 리스트: 속도느림, 메모리 용량 차지 많다.
2. 배열(array):속도빠름, 메모리 적게 차지
넘파이 배열과 리스트의 차이점
-배열은 모두 같은 자료형, 원소 개수 변경 못함.
-리스트는 다른 자료형 넣을수 있고, 원소 갯수 변경 가능.
-배열은 파이썬에서 제공하지 않음.
-파이썬 환경에서 넘파이 패키지를 활용하여 배열을 사용할 수 있음.

3. 넘파이: 수치해석 패키지, 다차원 배열 구조. 
벡터, 행렬을 사용하는 선행대수 계산시 사용.
넘파이 배열 연산 빠름(벡터화 연산)

"""


In [4]:
#1차원 배열
import numpy

ar=numpy.array([0,1,2,3,4])
ar
type(ar) #numpy.ndarray(nd:n dimension)
#이미지 데이터를 행렬로 나타낸다. 픽셀의 값을 그런식으로 표현.



numpy.ndarray

In [ ]:
# 100*100 크기의 이미지(픽셀:10000개) - 1만 차원, 픽셀 하나당 1개 차원.
# 0~255사이의 gray scale
# => 몇 차원? 1만 차원.
# 고화질 이미지 데이터를 처리할려면 컴퓨터의 성능이 좌우. 
# 고속 처리 기술이 필요하기때문에 기술이 발달. -> 하둡
# 배열이 속도가 빠르다(벡터 연산)
# => 삼성 8k TV AI기술 적용한거. 

# 공부하는 내용을 회사 직무에 어떻게 적용할지 생각하면서 공부하고, 자기소개서에 
# 녹여야 한다.




In [2]:
data = list(range(0,10))
#data에 저장된 모든 값들에 대해 2배

ans=[]
for d in data:
    ans.append(2*d)
     
print(ans)

#시간 복잡도: 연산 결과가 나오기까지 수행되는 라인의 수(CPU와 관련, 연산속도)
#공간 복잡도(Memory): 




[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [ ]:
#시간 복잡도의 예; CPU와 관련, 연산속도와 관련
data = list(range(0,10))
#data에 저장된 모든 값들에 대해 2배
sum=0
d=100
print(d*(d+1)/2)  #0(1)


for d in data:
    sum += d #0(n)
     
print(ans)

#컴퓨터의 능력도 좋아져야 하지만, 알고리즘의 능력도 좋아야 시간을 줄일수 있다.

In [3]:
ans=[]
data = list(range(0,11))
for d in data:
    ans.append(d*2)
print(ans)



[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


In [10]:
import numpy as np
x=np.array(data)
x*2 #벡터화 연산:for 문 사용 x, 한번의 연산. 리스트와 다르다.
# data*2 # 똑같은 자신 2번 나온다.

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [13]:
a=np.array([1,2,3])#요소간 연산. Element wise product(sum, add)
b=np.array([4,5,6])
a2=[1,2,3]
b2=[4,5,6]





In [20]:
2*a2+b2 #리스트의 덧셈은 append와 같다. [1, 2, 3, 1, 2, 3, 4, 5, 6]
2*a+b #요소간 연산. Element wise product(sum, add). => 벡터화 연산
#array([ 6,  9, 12])




array([ 6,  9, 12])

In [27]:
#a
#a2==2 #False
a==2 #array([False,  True, False]). 각각의 요소에 대해 가능. #논리연산 사용가능
#a2>2 #type Error: not supported 'list' and 'int'
a>2 #array([False, False,  True]), 비교연산에서 사용가능



array([False, False,  True])

In [ ]:
#2차원 배열(행렬, matrix)
#가로줄: 행 column, 세로줄: 열 row



In [28]:
#2차원 배열: 리스트의 리스트
m=np.array([[0,1,2],[3,4,5]])
m
#열: 안쪽 리스트 길이. 가로 크기
#행: 바깥쪽 리스트의 길이. 세로 크기
#2행 3열
# 0 1 2 
# 3 4 5
# array([[0, 1, 2],
#        [3, 4, 5]])


array([[0, 1, 2],
       [3, 4, 5]])

In [32]:
len(m) #2, 행의 갯수
m[0] #array([0, 1, 2])
m[1] #array([3, 4, 5])
len(m[0]) #3, 열의 갯수


3

In [42]:
#3차원배열: 리스트의 리스트의 리스트
m=np.array([[[1,2,3,4],
         [5,6,7,8],
         [9,10,11,12]],
        [[31,2,3,4],
         [35,6,7,8],
         [39,10,11,12]]])
#2행 3열. 요소(4개): 4깊이(면)
#2*3*4 
len(m) #2. 3번째 대괄호 기준으로 안에 2개로된 대괄호 2개 존재
len(m[0]) #3 # 2개로 된 대괄호 안에 1개 괄호들로 이루어진 갯수
len(m[0][0]) #4
print(m.ndim) #3, 3차원
print(m.shape) #(2, 3, 4)

3
(2, 3, 4)


In [38]:
a=np.array([4,5,6])
a.ndim#배열의 차원. #we
a.shape #배열의 크기 #(3,)



(3,)

In [40]:
a=np.array([[0,1,2],[3,4,5]])
a.ndim #배열의 차원.
a.shape

(2, 3)

In [63]:
#카페 업로드
#1번
import numpy as np
a=[3,2,1,-4,-7,-9,8,-5,3,-1]
#연속으로 숫자 3개를 곱했을때 얻어지는 결과값이 가장 큰 구간이 어디인지 출력,.
cont_mul=[]
for i in range(len(a)-3):
    cont_mul += [a[i]*a[i+1]*a[i+2]]
    
maxium_peri=max(cont_mul)
print(maxium_peri)
print()



504


In [ ]:
#2번
#숫자 2*2 영역을 구성하는 수를 곱했을때 얻어지는 결과값이 가장 큰 구간이 어디인지 출력,.
c=np.array[[3, 1,-2],
           [2, 1,-3],
           [-2,0,-7]]



In [56]:
a=np.array([3,2,1,-4,-7,-9,8,-5,3,-1])
a[0]* a[1]


6

In [76]:
#array slicing 슬라이싱(참조)
ar=np.array([[1,2,3,4],[5,6,7,8]])
ar
ar[0]
ar[0,:]#첫번째 행 전체 #array([1, 2, 3, 4])
ar[:,1]#2번째 열 전체 #array([2, 6])

ar[1,1:] #array([6, 7, 8]) #두번째 행에서 두번째 열부터 마지막까지

ar[:2, :2] #표기방법이 다양하다.
ar[:, :2]
ar[:, 0:2]

array([[1, 2],
       [5, 6]])

In [101]:
#Indexing 인덱싱: 데이터 1개를 참조
#slicing 슬라이싱: 데이터 여러개를 참조
ar=np.array([0,1,2])
ar[1] #1
ar[-1] #2


ar=np.array([[1,2,3,4],[5,6,7,8]])
ar[0][0] #1
ar[0]#다차원 배열에서는 컴마

#6추출
ar[1][1]
ar[1,1]
ar[-1,1]

6

In [93]:
#불린 참조:조건에 대해 만족하는 값을 추출
ar=np.array([2,3,4,5])
bidx=np.array([True, True, False, True])#논리값
ar[bidx]#array([2, 3, 5])#True 값만 가지는 것만 추출. boolin 참조.
ar[ar != 4] #array([2, 3, 5])

#ar 요소값이 짝수인것들만 추출
ar %2 ==0 #array([ True, False,  True, False])
ar[ar %2 ==0] #array([2, 4])

#ar 요소값이 3보다 큰 값들만 추출
ar>3 #array([False, False,  True,  True])
ar[ar>3] #array([4, 5])


array([4, 5])

In [102]:
#정수 참조 추출
ar=np.array([2,3,4,5])
idx=np.array([0,3])
ar[idx] #array([2, 5])

idx=np.array([0,0,1,1])
ar[idx] #array([2, 2, 3, 3])



array([2, 2, 3, 3])

In [127]:
ar=np.array([[1,2,3,4],[5,6,7,8]])
ar[:,[0,3]]
#ar[0,[0,3]]#array([1, 4])
#[[1,5],
# [4,8]]
ar[:,[True,False,False,True]]


array([[1, 4],
       [5, 8]])

In [140]:
ar=np.array([[1,2,3,4],[5,6,7,8]])
ar[:]#ar 전체 행
ar#ar 배열 전체
ar[:,:] #전체 행 전체 열
ar=np.array([[1,2,3,4],
             [15,16,17,18],
             [25,26,27,28],
             [35,36,37,38]])
ar[[2,0],:]
ar[[2,0,-1],:]
ar[[2,0],:]


array([[25, 26, 27, 28],
       [ 1,  2,  3,  4],
       [35, 36, 37, 38]])

In [ ]:
#원데이터:csv, tsv, txt, xls, xlsx, json,

#pandas:원데이터를 데이터프레임(엑셀 시트)으로 읽어서
#Numpy: 원데이터를 다차원배열으로 읽어서 처리한다.


In [161]:
import pandas as pd
csvTest=pd.read_csv("text_csv.csv") # read_csv는 ","로 구분하는 함수
#csvTest
type(csvTest)

pandas.core.frame.DataFrame

In [165]:
csvTest

ID LAST_NAME  AGE
0   1       KIM   25
1   2       LEE   22
2   3      PARK   33
3   4      CHOI   24
4   5       CHO   30

In [162]:
csvTest.shape # (5,3): 튜플


(5, 3)

In [168]:
# test_text.txt
# 구분자:|
text=pd.read_csv("test_text.txt", sep="|") #첫번째 줄을 Header로 읽어 버린다. 
text
#text.shape (5, 3)
#text.shape (5,1)
#행 인덱스 : 맨 왼쪽.
#ID 제목쪽: 열 인덱스(ID, LAST_NAME, AGE)

ID LAST_NAME  AGE
0   1       KIM   25
1   2       LEE   22
2   3      PARK   33
3   4      CHOI   24
4   5       CHO   30

In [187]:
#문제1번
k = np.array([[ 0,  1,  2,  3,  4],
              [ 5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14]])
k[1,2] # \value  7 indexing
k[2,4] #value 14 indexing
k[1,1:3] #array [6,7] slicing
k[1:,2] #array [7,12] slicing
k[:2,3:5] #array [[3,4],[8,9]] slicing

array([[3, 4],
       [8, 9]])

In [211]:
#문제 2번
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
              11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

a2=x[x % 3 ==0] #3의 배수 #array([ 3,  6,  9, 12, 15, 18])
b2=x[x % 4==1] #4로 나누면 1이 남는 수 #array([ 1,  5,  9, 13, 17])

x[(x % 3 ==0) & (x % 4==1)] #array([9])
# img[(img < 200) & (img > 150)] = 0
# img[(img >= 200) | (img <= 150)] = 0

array([9])

In [224]:
import numpy as np
a=np.array([0]*100,[0]*100)
a


TypeError: data type not understood

In [1]:
listdata=[]
data=[3,2,1,-4,-7,-9,8,-5,3,-1]
print("문제1")
for i in range(0,8):
    listdata.append(data[i]*data[i+1]*data[i+2])
print(listdata)
for i in range(0,8):
    if listdata[i]==max(listdata):
        print("max는 :",max(listdata))
        print("(",data[i],",",data[i+1],",",data[i+2],"), ",end="")
        print("data[",i,"~",i+2,"] 구간",sep="")

문제1
[6, -8, 28, -252, 504, 360, -120, 15]
max는 : 504
( -7 , -9 , 8 ), data[4~6] 구간


In [6]:
import numpy as np
# 각 열의 상자개수  입력받기
a = input() #74200607

# 100x100 matrix 생성 대신 8x9
h = 8
v = 9
room = np.array([[0]*h]*v)

# 입력 받은 상자 개수대로 상자 위치 표시(상자가 있으면 1, 없으면 0)
for i in range(h):
    j = 0
    for k in range(int(a[i])):
        room[-(j+1),i] = 1
        j += 1
# 룸
print(room)
print('-'*20)

#낙차 값구하기
c = 0
for i in range(v):
    for j in range(h):
# 0의 개수가 상자가 낙차할 거리 => room[j,i]이 1일때 그 위치 오른쪽의 0의 개수 체크
# 0의 개수가 저장되어 있는 0의 개수보다 크면 그값과 그 위치 저장
# 위치는 회전된 위치로 저장
        if room[i,j] == 1 and list(room[i,j:]).count(0) > c: 
            c = list(room[i,j:]).count(0)
            location = [j,room.shape[0]-(i+1)]
print(c)
print(location)


74200607
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 1 0 1]
 [1 0 0 0 0 1 0 1]
 [1 1 0 0 0 1 0 1]
 [1 1 0 0 0 1 0 1]
 [1 1 1 0 0 1 0 1]
 [1 1 1 0 0 1 0 1]]
--------------------
6
[0, 6]
