In [1]:
"""
정규화: "0~1" 사이의 범위로 데이터를 표준화

5 3 1 7 9 => 0 ~ 1 =>  (데이터 -1) 각 데이터 - 최소값 / (9-)1 최대-최소
5-1/ 9-1 =>0.5
3-1/ 9-1 =>
1-1/ 9-1 => 0
"""

'\n정규화: "0~1" 사이의 범위로 데이터를 표준화\n\n5 3 1 7 9 => 0 ~ 1 =>  (데이터 -1) 각 데이터 - 최소값 / (9-)1 최대-최소\n5-1/ 9-1 =>0.5\n3-1/ 9-1 =>\n1-1/ 9-1 => 0\n'

'\n정규화: "0~1" 사이의 범위로 데이터를 표준화\n\n5 3 1 7 9 => 0 ~ 1 =>  (데이터 -1) 각 데이터 - 최소값 / (9-)1 최대-최소\n5-1/ 9-1 =>0.5\n3-1/ 9-1 =>\n1-1/ 9-1 => 0\n'

In [9]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
#sklearn 머신러닝, 기계학습 하는 좋은 패키지. 


In [10]:
data=np.array([[10,-10,2],
              [5,0,6],
              [0,7,4]])
data
#열 하나 하나 변수, 각각의 행은 인스턴스. 




array([[ 10, -10,   2],
       [  5,   0,   6],
       [  0,   7,   4]])

In [11]:
# data.max() #10 #data 배열 전체에서 최대값
# data.max(axis=0) #array([10,  7,  6]) #각 열 단위 최대값
# data.max(axis=1) #array([10,  6,  7]) #각 행 단위 최대값
# data.min() #-10

#data.max(axis=0)-data.min(axis=0) #array([10, 17,  4]) # 분모

#1) 직접 손으로 하는 방법(공식 만드는 방법)
data_mm=(data-data.min(axis=0)) / (data.max(axis=0)-data.min(axis=0))
data_mm



array([[1.        , 0.        , 0.        ],
       [0.5       , 0.58823529, 1.        ],
       [0.        , 1.        , 0.5       ]])

In [12]:
#2) MinMaxScaler함수를 사용. 
mms= MinMaxScaler() # MinMaxScaler 함수 호출
datamms=mms.fit_transform(data)
#MinMaxScaler(copy=True, feature_range=(0, 1))
datamms


array([[1.        , 0.        , 0.        ],
       [0.5       , 0.58823529, 1.        ],
       [0.        , 1.        , 0.5       ]])

In [13]:
#3) sklearn.preprocessing 패키지 사용.
from sklearn.preprocessing import minmax_scale
datamm=minmax_scale(data,axis=0)
datamm



array([[1.        , 0.        , 0.        ],
       [0.5       , 0.58823529, 1.        ],
       [0.        , 1.        , 0.5       ]])

In [14]:
#이항변수화: 연속형변수를 기준이하 -> '0', 기준초과 -> '1'
#시시각각 변화하는 데이터에 적용. 임계치 or 기준치를 정해놓고 변환
#확률변수 X가 이항분포를 따른다고 했을때, 
#'0' 또는 '1'값을 갖는 이항변수화가 필요 
#베르누이시행(시도): 동일한 실험을 계속 반복, 성공(1), 실패(0) 두가지 경우만 존재.
#성공확률이 p인 베르누이시행을 n번 수행.
#성공확률 횟수를 x라고 하면,
#확률변수 x는 모수 n과 p인 이항분포를 따른다.

"""
주사위: '3'이 나올 확률
'3'이 나올 확률(성공): 1/6
실패 확률 : 1/6

A, B, C, D
(A만 성공, B만 성공, C만 성공, D만 성공)

A만 성공, 나머지 실패: 1/6*(5/6)^3 =0.09(가정)
B만 성공, 나머지 실패: 1/6*(5/6)^3
C만 성공, 나머지 실패: 1/6*(5/6)^3
D만 성공, 나머지 실패: 1/6*(5/6)^3
0.09(성공확률, p) * 4(시나리오수, n) = 0.36

성공확률(p) * 시나리오수(n)

"""



"\n주사위: '3'이 나올 확률\n'3'이 나올 확률(성공): 1/6\n실패 확률 : 1/6\n\nA, B, C, D\n(A만 성공, B만 성공, C만 성공, D만 성공)\n\nA만 성공, 나머지 실패: 1/6*(5/6)^3 =0.09(가정)\nB만 성공, 나머지 실패: 1/6*(5/6)^3\nC만 성공, 나머지 실패: 1/6*(5/6)^3\nD만 성공, 나머지 실패: 1/6*(5/6)^3\n0.09(성공확률, p) * 4(시나리오수, n) = 0.36\n\n성공확률(p) * 시나리오수(n)\n\n"

In [15]:
from sklearn.preprocessing import Binarizer


In [16]:
bina=Binarizer().fit(data) # default: Binarizer(copy=True, threshold=0.0)
bina  #Binarizer(threshold=5).fit(data)
#threshold 임계값. 속성 부여 가능(기준 설정)


Binarizer(copy=True, threshold=0.0)

In [17]:
bina.transform(data) #0보다 크면 1, 0보다 작으면 0

array([[1, 0, 1],
       [1, 0, 1],
       [0, 1, 1]])

In [18]:
data

array([[ 10, -10,   2],
       [  5,   0,   6],
       [  0,   7,   4]])

In [19]:
bina1=Binarizer(threshold=5.5).fit(data) #실수, 정수 가능 # 5.5까지 포함
bina1
bina1.transform(data)

array([[1, 0, 0],
       [0, 0, 1],
       [0, 1, 0]])

In [20]:
from sklearn.preprocessing import binarize
data=np.array([[10,-10,2],
              [5,0,6],
              [0,7,4]])


In [21]:
binarize(data) 
binarize(data, threshold=5)
binarize(data, threshold=5, copy=True) #copy = True default
binarize(data, threshold=5, copy=False)
#copy=False이면, 원본 데이터로 binarize하기 때문에

array([[1, 0, 0],
       [0, 0, 1],
       [0, 1, 0]])

In [22]:
#바이너라이저(Binarizer): 연속형 변수를 이상변수화
#원핫인코더(OneHotEncoder): 범주형 변수를 이항변수화

"""
연령대: 20대 -> 0, 30대 -> 1, 40대 -> 2
성별: 남성 -> 0, 여성 -> 1
학점: A:0, B:1, C:2, D:3, E:4

길이 5로 잡고, 추상화 작업 나머지는 0으로. 
01234
10000(A)
01000(B)
...
00001(F)

ex) 20대 여성 B학점
    100   01  01000
    30대 남성 D학점
    010   10  00010

"""




'\n연령대: 20대 -> 0, 30대 -> 1, 40대 -> 2\n성별: 남성 -> 0, 여성 -> 1\n학점: A:0, B:1, C:2, D:3, E:4\n\n길이 5로 잡고, 추상화 작업 나머지는 0으로. \n01234\n10000(A)\n01000(B)\n...\n00001(F)\n\nex) 20대 여성 B학점\n    100   01  01000\n    30대 남성 D학점\n    010   10  00010\n\n'

In [23]:
from sklearn.preprocessing import OneHotEncoder
#[성별, 연령, 학점]
data=np.array([[0,0,0],
                [0,1,1],
                [0,2,2],
                [1,0,3],
                [1,1,4]
                ])


In [24]:
ohe=OneHotEncoder() #Onehot Encoder 객체 생성
ohe.fit(data)




C:\Users\student\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


OneHotEncoder(categorical_features=None, categories=None, drop=None,
              dtype=<class 'numpy.float64'>, handle_unknown='error',
              n_values=None, sparse=True)

In [25]:
ohe.active_features_
#array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)\
#[남,여, 20,30,40, a,b,c,d,f]

ohe.n_values_ #array([2, 3, 5])
#범주 갯수

ohe.feature_indices_# array([ 0,  2,  5, 10], dtype=int32)
#성별: 0이상 2미만, 
#연령: 2이상 5미만, 
#학점:5이상 10미만

C:\Users\student\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:100: DeprecationWarning: The ``active_features_`` attribute was deprecated in version 0.20 and will be removed 0.22.
  warnings.warn(msg, category=DeprecationWarning)
C:\Users\student\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:100: DeprecationWarning: The ``n_values_`` attribute was deprecated in version 0.20 and will be removed 0.22.
  warnings.warn(msg, category=DeprecationWarning)
C:\Users\student\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:100: DeprecationWarning: The ``feature_indices_`` attribute was deprecated in version 0.20 and will be removed 0.22.
  warnings.warn(msg, category=DeprecationWarning)


array([ 0,  2,  5, 10], dtype=int32)

In [26]:
#하려는 작업
#범주형 데이터 -> 이항변수화
data=np.array([[1,2,3]]) #여성 40대 D학점
ohe.transform(data)
ohe.transform(data).toarray()
#array([[0., 1., 0., 0., 1., 0., 0., 0., 1., 0.]])

array([[0., 1., 0., 0., 1., 0., 0., 0., 1., 0.]])

In [27]:
df = pd.DataFrame({'C1': np.random.randn(20),
   'C2': ['a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a',
   'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b']})
df

C1 C2
0   1.180713  a
1  -1.256841  a
2  -1.644262  a
3   0.529206  a
4  -0.502229  a
5  -0.973941  a
6  -0.075223  a
7  -0.697571  a
8  -0.572436  a
9   0.614053  a
10 -0.232246  b
11  1.101809  b
12  1.341290  b
13 -0.518954  b
14 -0.087020  b
15 -0.492439  b
16 -0.462842  b
17  1.103542  b
18  0.864026  b
19 -0.107243  b

In [28]:
"""
np.digitize함수, np.where 함수: 연속형 변수 -> 이산화 
이항변수화: '0' or '1' 값을 갖는 변수를 만드는 것
이산(형)화: 연속형 변수를 2개 이상의 범주를 갖는 변수로 변환.
ex) 점수: 75(연속형 변수) -> 학점: A/B/C/D/F 5개의 범주로 나누는것 => 이산화
범주(Category)
"""
np.random.seed(10) #42, 777,1004 #seed를 동일하게 주면 난수도 동일하게 나온다.
np.random.randn(1)



array([1.3315865])

In [29]:
"""
df의 c1열 20개 data 구성
10개 bin으로 균등하게 나눔

"""
#df['c1']
df.C1.min() #-1.2657
df.C1.max() #2.28197
bins=np.linspace(df.C1.min(), df.C1.max(), 10) #공간(크기)을 균등(하게 나누는 메서드
bins
#10개 구간으로 나누었는데, 그 구간을 토대로 이산화 가능 


array([-1.64426233, -1.31253428, -0.98080623, -0.64907818, -0.31735013,
        0.01437793,  0.34610598,  0.67783403,  1.00956208,  1.34129013])

In [30]:
df.C1
df['C1_bin']=np.digitize(df['C1'],bins)
df# 구간마다 포함된 갯수. 범주 확인

C1 C2  C1_bin
0   1.180713  a       9
1  -1.256841  a       2
2  -1.644262  a       1
3   0.529206  a       7
4  -0.502229  a       4
5  -0.973941  a       3
6  -0.075223  a       5
7  -0.697571  a       3
8  -0.572436  a       4
9   0.614053  a       7
10 -0.232246  b       5
11  1.101809  b       9
12  1.341290  b      10
13 -0.518954  b       4
14 -0.087020  b       5
15 -0.492439  b       4
16 -0.462842  b       4
17  1.103542  b       9
18  0.864026  b       8
19 -0.107243  b       5

In [31]:
#구간별로 요약 통계 구할수 있다. 범주간 평균 차이 구할 수 있다.
#독립성 검정, indexing 

df.C1_bin #
#df.groupby('C1_bin') #<pandas.core.groupby.generic.DataFrameGroupBy object at 0x000001C5FFC8B348>
df.groupby('C1_bin')['C1'].size() #C1_bin열 그룹화. 그룹화에 속하는 건수를 조사 가능
df.groupby('C1_bin')['C1'].mean()#그룹화된 평균.
df.groupby('C1_bin')['C1'].std()#그룹화 C1_bin의 분산. 데이터가 1개밖에 없는것들은 NaN. 
df.groupby('C1_bin')['C2'].value_counts() #데이터 갯수를 카운트.

df[df['C1_bin'] ==4] #그룹화후 특정 그룹을 추출. 총 10개 그룹


C1 C2  C1_bin
4  -0.502229  a       4
8  -0.572436  a       4
13 -0.518954  b       4
15 -0.492439  b       4
16 -0.462842  b       4

In [32]:
#get_dummies 함수를 사용하여 OneHotEncoding 만들수 있다.

# pd.get_dummies(): 가변수 생성
df['C1_bin']
pd.get_dummies(df['C1_bin'])
# OneHotEncoding 완성

pd.get_dummies(df['C1_bin'], prefix='C1') #prefix='C1' 접두어 설정 가능
# 모델 = x1*가중치 + x2*가중치 + ... + x10*가중치+ 바이어스




C1_1  C1_2  C1_3  C1_4  C1_5  C1_7  C1_8  C1_9  C1_10
0      0     0     0     0     0     0     0     1      0
1      0     1     0     0     0     0     0     0      0
2      1     0     0     0     0     0     0     0      0
3      0     0     0     0     0     1     0     0      0
4      0     0     0     1     0     0     0     0      0
5      0     0     1     0     0     0     0     0      0
6      0     0     0     0     1     0     0     0      0
7      0     0     1     0     0     0     0     0      0
8      0     0     0     1     0     0     0     0      0
9      0     0     0     0     0     1     0     0      0
10     0     0     0     0     1     0     0     0      0
11     0     0     0     0     0     0     0     1      0
12     0     0     0     0     0     0     0     0      1
13     0     0     0     1     0     0     0     0      0
14     0     0     0     0     1     0     0     0      0
15     0     0     0     1     0     0     0     0      0
16     0     0     0     1     0     0     0     0      0
17     0     0     0     0     0     0     0     1      0
18     0     0     0     0     0     0     1     0      0
19     0     0     0     0     1     0     0     0      0

In [33]:
#np.where(조건, 참, 거짓)
df['C1']>=df.C1.mean()
df['h_l']=np.where(df['C1']>=df.C1.mean(), 'high','low') 
#df['h_l']열 추가하면서 higt, low 표시 -> 그룹 나누기 가능
df

#그룹화 
df.groupby('h_l')['C1'].size() 
df.groupby('h_l')['C1'].mean() 
df.groupby('h_l')['C1'].std()



h_l
high    0.302560
low     0.468396
Name: C1, dtype: float64

In [34]:
Q1=np.percentile(df['C1'],25) #percentile 4분위 나누는 함수
Q3=np.percentile(df['C1'],25)
#연습문제: C1열 값 <= Q1 then df['h_m_l']=l
#C1열 값 > Q1 and <= Q3 df['h_m_l']=m
#else then df['h_m_l']=h
df['h_m_l']=np.where(df['C1']>=Q3,'high',
                        np.where(df['C1']>=Q1,'medium','low'))

df['h_m_l']

0     high
1      low
2      low
3     high
4     high
5      low
6     high
7      low
8      low
9     high
10    high
11    high
12    high
13    high
14    high
15    high
16    high
17    high
18    high
19    high
Name: h_m_l, dtype: object

In [35]:
df

C1 C2  C1_bin   h_l h_m_l
0   1.180713  a       9  high  high
1  -1.256841  a       2   low   low
2  -1.644262  a       1   low   low
3   0.529206  a       7  high  high
4  -0.502229  a       4   low  high
5  -0.973941  a       3   low   low
6  -0.075223  a       5   low  high
7  -0.697571  a       3   low   low
8  -0.572436  a       4   low   low
9   0.614053  a       7  high  high
10 -0.232246  b       5   low  high
11  1.101809  b       9  high  high
12  1.341290  b      10  high  high
13 -0.518954  b       4   low  high
14 -0.087020  b       5   low  high
15 -0.492439  b       4   low  high
16 -0.462842  b       4   low  high
17  1.103542  b       9  high  high
18  0.864026  b       8  high  high
19 -0.107243  b       5   low  high

In [36]:
"""
데이터 재구조화
- 피봇테이블(피벗테이블); 2개의 함수가 존재. pivot, pivot_table
- 스택(stack,unstack) 쌓거나 안쌓거나
- 멜트(melt) 녹이는것
- wide_to_long 넓고 길게 나타내는 
- crosstab
"""

'\n데이터 재구조화\n- 피봇테이블(피벗테이블); 2개의 함수가 존재. pivot, pivot_table\n- 스택(stack,unstack) 쌓거나 안쌓거나\n- 멜트(melt) 녹이는것\n- wide_to_long 넓고 길게 나타내는 \n- crosstab\n'

In [37]:
data = pd.DataFrame({'cust_id': ['c1', 'c1', 'c1', 'c2', 'c2', 'c2', 'c3', 'c3', 'c3'],
                     'prod_cd': ['p1', 'p2', 'p3', 'p1', 'p2', 'p3', 'p1', 'p2', 'p3'],
                     'grade' : ['A', 'A', 'A', 'A', 'A', 'A', 'B', 'B', 'B'],
                     'pch_amt': [30, 10, 0, 40, 15, 30, 0, 0, 10]})

#데이터들을 원하는 열들을 재구조화 해서 분석할떄 사용
data

cust_id prod_cd grade  pch_amt
0      c1      p1     A       30
1      c1      p2     A       10
2      c1      p3     A        0
3      c2      p1     A       40
4      c2      p2     A       15
5      c2      p3     A       30
6      c3      p1     B        0
7      c3      p2     B        0
8      c3      p3     B       10

In [38]:
#     p1  p2  p3
#cid
#c1  30  10   0
#c2  40  15   30
#c3  ...


#1) pivot 함수
data.pivot(index='cust_id', columns='prod_cd', values='pch_amt')

prod_cd  p1  p2  p3
cust_id            
c1       30  10   0
c2       40  15  30
c3        0   0  10

In [39]:
# 2) pivot_table 함수(pandas안에 있다)

pd.pivot_table(data, index='cust_id', columns='prod_cd', values='pch_amt') 
#원래는 이렇게 pandas
#pivot에서는 안되지만, pivot_table에선 가능한 작업들이 많다. 따라서, table 사용하기


prod_cd  p1  p2  p3
cust_id            
c1       30  10   0
c2       40  15  30
c3        0   0  10

In [40]:
# data.pivot(index=['cust_id','grade'],
#            columns='prod_cd', 
#            values='pch_amt')
#에러 발생(Pivot)

pd.pivot_table(data, index=['cust_id','grade'],
                     columns='prod_cd', 
                     values='pch_amt')
#No Error(Pivot_table)



prod_cd        p1  p2  p3
cust_id grade            
c1      A      30  10   0
c2      A      40  15  30
c3      B       0   0  10

In [65]:
pd.pivot_table(data, index='cust_id',
                     columns=['grade', 'prod_cd'],
                     values='pch_amt')


grade       A                B           
prod_cd    p1    p2    p3   p1   p2    p3
cust_id                                  
c1       30.0  10.0   0.0  NaN  NaN   NaN
c2       40.0  15.0  30.0  NaN  NaN   NaN
c3        NaN   NaN   NaN  0.0  0.0  10.0

In [67]:
#pivot_table: 집계함수 제공
pd.pivot_table(data, index='grade',columns='prod_cd',values='pch_amt')
#default: 평균이 적용

pd.pivot_table(data, index='grade',columns='prod_cd',values='pch_amt', aggfunc=np.mean)
#aggfunc=np.mean 생략 되어 있다. 

pd.pivot_table(data, index='grade',columns='prod_cd',values='pch_amt', aggfunc=np.sum)

#data.pivot(data, index='grade',columns='prod_cd',values='pch_amt', aggfunc=np.mean)
#Error : multiple values 문법적으로 불가능 => pivot_table 기억하고 사용하기.




prod_cd  p1  p2  p3
grade              
A        70  25  30
B         0   0  10

In [68]:

# stack():위에서 아래로 쌓는것
# Unstack():쌓여 있는 것을 옆으로 놓는것(왼->오른)

mul_index = pd.MultiIndex.from_tuples([('cust_1', '2020'), ('cust_1', '2021'),

   ('cust_2', '2020'), ('cust_2', '2021')])  

mul_index

data = pd.DataFrame(data=np.arange(16).reshape(4, 4),

   index=mul_index,

   columns=['prd_1', 'prd_2', 'prd_3', 'prd_4'],

   dtype='int')
data

# data = DataFrame({'cust_ID' : ['C_001', 'C_001', 'C_002', 'C_002'],

#    'prd_CD' : ['P_001', 'P_002', 'P_001', 'P_002'],

#    'pch_cnt' : [1, 2, 3, 4],
# 'pch_amt' : [100, 200, 300, 400]})



prd_1  prd_2  prd_3  prd_4
cust_1 2020      0      1      2      3
       2021      4      5      6      7
cust_2 2020      8      9     10     11
       2021     12     13     14     15

In [ ]:
datastd=data.stack()
datastd

In [ ]:
datastd.index

In [ ]:
data

In [ ]:

data.ix['cust_2','prd_4']=np.nan
data


In [ ]:
data.stack()
#np.nan은 출력되지 않음
data.stack(dropna=False)
#nan 출력됨


In [69]:
#melt
data =pd.DataFrame({'cust_ID' : ['C_001', 'C_001', 'C_002', 'C_002'],
                        'prd_CD' : ['P_001', 'P_002', 'P_001', 'P_002'],
                        'pch_cnt' : [1, 2, 3, 4],
                        'pch_amt' : [100, 200, 300, 400]})
data



cust_ID prd_CD  pch_cnt  pch_amt
0   C_001  P_001        1      100
1   C_001  P_002        2      200
2   C_002  P_001        3      300
3   C_002  P_002        4      400

In [70]:
pd.melt(data, id_vars=['cust_ID','prd_CD'])

cust_ID prd_CD variable  value
0   C_001  P_001  pch_cnt      1
1   C_001  P_002  pch_cnt      2
2   C_002  P_001  pch_cnt      3
3   C_002  P_002  pch_cnt      4
4   C_001  P_001  pch_amt    100
5   C_001  P_002  pch_amt    200
6   C_002  P_001  pch_amt    300
7   C_002  P_002  pch_amt    400

In [71]:
pd.melt(data, id_vars=['cust_ID','prd_CD'])
pd.melt(data, id_vars=['cust_ID','prd_CD'],var_name='CD', value_name='VAL')


cust_ID prd_CD       CD  VAL
0   C_001  P_001  pch_cnt    1
1   C_001  P_002  pch_cnt    2
2   C_002  P_001  pch_cnt    3
3   C_002  P_002  pch_cnt    4
4   C_001  P_001  pch_amt  100
5   C_001  P_002  pch_amt  200
6   C_002  P_001  pch_amt  300
7   C_002  P_002  pch_amt  400

In [72]:

pew=pd.read_csv("pew.csv")
pew.head() #5개만 가지고 오는것
pew.iloc[:,0:6] #$40-50k까지


religion  <$10k  $10-20k  $20-30k  $30-40k  $40-50k
0                  Agnostic     27       34       60       81       76
1                   Atheist     12       27       37       52       35
2                  Buddhist     27       21       30       34       33
3                  Catholic    418      617      732      670      638
4        Don’t know/refused     15       14       15       11       10
5          Evangelical Prot    575      869     1064      982      881
6                     Hindu      1        9        7        9       11
7   Historically Black Prot    228      244      236      238      197
8         Jehovah's Witness     20       27       24       24       21
9                    Jewish     19       19       25       25       30
10            Mainline Prot    289      495      619      655      651
11                   Mormon     29       40       48       51       56
12                   Muslim      6        7        9       10        9
13                 Orthodox     13       17       23       32       32
14          Other Christian      9        7       11       13       13
15             Other Faiths     20       33       40       46       49
16    Other World Religions      5        2        3        4        2
17             Unaffiliated    217      299      374      365      341

In [73]:
pd.melt(pew, id_vars='religion') #고정해야할것 id_vars
pd.melt(pew, id_vars='religion', var_name='income', value_name='count')


religion              income  count
0                 Agnostic               <$10k     27
1                  Atheist               <$10k     12
2                 Buddhist               <$10k     27
3                 Catholic               <$10k    418
4       Don’t know/refused               <$10k     15
..                     ...                 ...    ...
175               Orthodox  Don't know/refused     73
176        Other Christian  Don't know/refused     18
177           Other Faiths  Don't know/refused     71
178  Other World Religions  Don't know/refused      8
179           Unaffiliated  Don't know/refused    597

[180 rows x 3 columns]

In [74]:
billboard=pd.read_csv("billboard.csv")
billboard


year            artist                    track  time date.entered  wk1  \
0    2000             2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26   87   
1    2000           2Ge+her  The Hardest Part Of ...  3:15   2000-09-02   91   
2    2000      3 Doors Down               Kryptonite  3:53   2000-04-08   81   
3    2000      3 Doors Down                    Loser  4:24   2000-10-21   76   
4    2000          504 Boyz            Wobble Wobble  3:35   2000-04-15   57   
..    ...               ...                      ...   ...          ...  ...   
312  2000       Yankee Grey     Another Nine Minutes  3:10   2000-04-29   86   
313  2000  Yearwood, Trisha          Real Live Woman  3:55   2000-04-01   85   
314  2000   Ying Yang Twins  Whistle While You Tw...  4:19   2000-03-18   95   
315  2000     Zombie Nation            Kernkraft 400  3:30   2000-09-02   99   
316  2000   matchbox twenty                     Bent  4:12   2000-04-29   60   

      wk2   wk3   wk4   wk5  ...  wk67  wk68  wk69  wk70  wk71  wk72  wk73  \
0    82.0  72.0  77.0  87.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
1    87.0  92.0   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
2    70.0  68.0  67.0  66.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
3    76.0  72.0  69.0  67.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
4    34.0  25.0  17.0  17.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
..    ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   ...   ...   
312  83.0  77.0  74.0  83.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
313  83.0  83.0  82.0  81.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
314  94.0  91.0  85.0  84.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
315  99.0   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
316  37.0  29.0  24.0  22.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   

     wk74  wk75  wk76  
0     NaN   NaN   NaN  
1     NaN   NaN   NaN  
2     NaN   NaN   NaN  
3     NaN   NaN   NaN  
4     NaN   NaN   NaN  
..    ...   ...   ...  
312   NaN   NaN   NaN  
313   NaN   NaN   NaN  
314   NaN   NaN   NaN  
315   NaN   NaN   NaN  
316   NaN   NaN   NaN  

[317 rows x 81 columns]

In [75]:
pd.melt(billboard, id_vars=['year', 'artist', 'track', 'time', 'date.entered'], var_name="week", value_name="rating")
#billboard.columns

year            artist                    track  time date.entered  \
0      2000             2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26   
1      2000           2Ge+her  The Hardest Part Of ...  3:15   2000-09-02   
2      2000      3 Doors Down               Kryptonite  3:53   2000-04-08   
3      2000      3 Doors Down                    Loser  4:24   2000-10-21   
4      2000          504 Boyz            Wobble Wobble  3:35   2000-04-15   
...     ...               ...                      ...   ...          ...   
24087  2000       Yankee Grey     Another Nine Minutes  3:10   2000-04-29   
24088  2000  Yearwood, Trisha          Real Live Woman  3:55   2000-04-01   
24089  2000   Ying Yang Twins  Whistle While You Tw...  4:19   2000-03-18   
24090  2000     Zombie Nation            Kernkraft 400  3:30   2000-09-02   
24091  2000   matchbox twenty                     Bent  4:12   2000-04-29   

       week  rating  
0       wk1    87.0  
1       wk1    91.0  
2       wk1    81.0  
3       wk1    76.0  
4       wk1    57.0  
...     ...     ...  
24087  wk76     NaN  
24088  wk76     NaN  
24089  wk76     NaN  
24090  wk76     NaN  
24091  wk76     NaN  

[24092 rows x 7 columns]

In [76]:
s=pd.Series(range(10))
s[3]=np.nan
s
s.count() #9 #누락값은 제외

df=pd.DataFrame(np.random.randint(5,size=(4,4)),dtype=float)# 5:0~4까지 범위
df

df.ix[2,3]=np.nan
df



C:\Users\student\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  if __name__ == '__main__':


0    1    2    3
0  1.0  0.0  1.0  2.0
1  0.0  1.0  0.0  2.0
2  0.0  4.0  3.0  NaN
3  4.0  3.0  0.0  3.0

In [ ]:
df.count()#4,4,4,3 (각 열의 데이터 개수)



In [ ]:
import seaborn as sns
titanic=sns.load_dataset("titanic")
titanic.head()

In [ ]:
titanic.count() #(각 열의 데이터 개수)
#Series일땐 nan 못 세고, DataFrame인 경우에는 Nan을 포함해서 센다.
#사실상 titanic은 dataFrame인데 count함수는 시리즈로 계산.

In [ ]:
np.random.seed(777)
s2=pd.Series(np.random.randint(6, size=100))
s2

In [ ]:
#s2.count() #시리즈에선 nan을 제외한 카운트
s2.value_counts()
#종류별로 데이터 갯수를 count

In [ ]:
df[0].value_counts() # 시리즈 단위로 Value_count해야한다.

In [ ]:
s2.value_counts().sort_index()#index 기준으로 정렬하고 하면, sort. 오름차순 정렬.

In [ ]:
s.sort_values() # 값을 기준으로 정렬(nan은 맨 마지막). 오름차순 정렬.

In [ ]:
s.sort_values(ascending=False) #ascending= False 내림차순. True가 default


In [ ]:
df.sort_values(by=3) #dataFrame에서는 sort_values by로 기준 설정 오름차순

In [ ]:
df.sort_values(by=[1,2]) #1번 열에서 '1'이 2개 있는데 2차 정렬할때 이런식으로 사용.
#1차 정렬, 2차 정렬 [1,2]를 기준으로 설정했다. 


In [ ]:
df=pd.DataFrame(np.random.randint(10,size=(4,8)))
df
df["Mysum"]=df.sum(axis=1) #각 행의 합
df


In [ ]:
df.sum(axis=0)#각 열의 합

In [ ]:
df.loc["total", :]=df.sum()
df

In [78]:
#실수, 데이터 -> 카테고리화
#cut(실수 값의 경계 지정)
#qcut(똑같은 구간으로 나눌때)
ages=[0,2,10,21,23,37,31,61,20,42,32,100]
bins=[1,15,25,35,60,99]
labels=["미성년자","청년","중년","장년","노년"]

cats=pd.cut(ages, bins, labels=labels) #labels 속성(왼), 이름(오)
cats

[NaN, 미성년자, 미성년자, 청년, 청년, ..., 노년, 청년, 장년, 중년, NaN]
Length: 12
Categories (5, object): [미성년자 < 청년 < 중년 < 장년 < 노년]

In [ ]:
cats.categories

In [ ]:
cats.codes #어느 범주에 있는지 index로 보여줌

In [79]:
df=pd.DataFrame(ages, columns=["ages"])
df


ages
0      0
1      2
2     10
3     21
4     23
5     37
6     31
7     61
8     20
9     42
10    32
11   100

In [80]:
df['age_cut']=pd.cut(ages, bins, labels=labels)
df

ages age_cut
0      0     NaN
1      2    미성년자
2     10    미성년자
3     21      청년
4     23      청년
5     37      장년
6     31      중년
7     61      노년
8     20      청년
9     42      장년
10    32      중년
11   100     NaN

In [81]:
data=np.random.randn(100)
data
cats=pd.qcut(data, 4, labels=["Q1","Q2","Q3","Q4"])
cats
pd.value_counts(cats)

Q4    25
Q3    25
Q2    25
Q1    25
dtype: int64

In [ ]:
#문제 1번. titanic
from sklearn.preprocessing import OneHotEncoder
import seaborn as sns
titanic=sns.load_dataset("titanic")
titanic





In [82]:
#OneHotEncoding "Pclass" 
pd.get_dummies(titanic['pclass'], prefix='Class') 


Class_1  Class_2  Class_3
0          0        0        1
1          1        0        0
2          0        0        1
3          1        0        0
4          0        0        1
..       ...      ...      ...
886        0        1        0
887        1        0        0
888        0        0        1
889        1        0        0
890        0        0        1

[891 rows x 3 columns]

In [83]:
#Age를 이산화(5개 구간으로 나눔)
titanic.age.max()
bins=np.linspace(titanic.age.min(), titanic.age.max(), 5)
titanic['ages']=np.digitize(titanic['age'],bins)

#Fare를 이산화(3개 구간으로 나눔)
bins2=np.linspace(titanic.fare.min(), titanic.fare.max(),3)
titanic['fares']=np.digitize(titanic['fare'],bins2)
titanic

#embarked를 OneHotEncoding
pd.get_dummies(titanic['embarked'], prefix='Port')




Port_C  Port_Q  Port_S
0         0       0       1
1         1       0       0
2         0       0       1
3         0       0       1
4         0       0       1
..      ...     ...     ...
886       0       0       1
887       0       0       1
888       0       0       1
889       1       0       0
890       0       1       0

[891 rows x 3 columns]

In [ ]:
#문제 2번. 리스트를 거꾸로 출력하는 반복문(2가지 방법)
#첫번째 방법: reversed 함수 사용
re_list=list(map(str,input("Reverse list: ")))
print(list(reversed(re_list)))

#두번째 방법: for문 활용
re_list2=list(map(str,input("Reverse list: ")))
for char in reversed(re_list2):
    print(list(char),end=" ")
    
# 세번째 방법: indexing 호출 방법
re_list3=list(map(str,input("Reverse list: ")))
print(re_list3[::-1])

# 네번째 방법:for문 indexing
re_list4=list(map(str,input("Reverse list: ")))
for char in range(len(re_list4)-1, -1,-1):
    print(re_list4[char],end=" ")

In [ ]:
#문제 3번 리스트에서 중복 값 제거.
ns=[1,3,5,1,3,5,1,3,5]
remove_list= list(set(ns))
print(remove_list)

In [ ]:
numbers = [2, 4, 6, 8, 10, 12, 14]

for i in range(len(numbers)-1, 0, -1):
    print((numbers[i]), end=",")
    

In [ ]:
#reverse()
#이 메소드는 아무런 값도 반환하지 않지만, 
#리스트에 있는 값의 순서를 거꾸로 뒤집습니다.
"""
list = [0,10,20,40]
list.reverse()
 
print(list)
 
# [40, 20, 10, 0]
"""

#reversed()
#이 메소드는 순서가 거꾸로 뒤집힌 리스트를 반환합니다.
"""
seqList = [1, 2, 4, 3, 5]
print(list(reversed(seqList)))
 
# [5, 3, 4, 2, 1]
 
array=[0, 10, 20, 40]
for i in reversed(array):
    print(i)

"""




In [ ]:
array=[0, 10, 20, 40]
for i in reversed(array):
    print(i, end=" ")

In [ ]:
seqList = [1, 2, 4, 3, 5]
list(reversed(seqList))


In [ ]:
re_list=list(map(str,input("Reverse list: ")))
print(list(reversed(re_list)))


In [ ]:
re_list2=list(map(str,input("Reverse list: ")))
for char in reversed(re_list2):
    print(list(char),end=" ")


In [ ]:
l = ['a', 'b', 'c', 'd', 'e']
print(l[::-1])  # ['e', 'd', 'c', 'b', 'a']

In [ ]:
re_list3=list(map(str,input("Reverse list: ")))
print(re_list3[::-1])

In [24]:
#문제 4번.
#bins = [1, 15, 25, 35, 60, 99]
#labels = ["미성년자", "청년", "중년", "장년", "노년"]
#타이타닉호 승객을 사망자와 생존자 그룹으로 나누고 각 그룹에 대해 '미성년자', '청년', '중년', '장년', '노년' 승객의 비율을 구한다. 
#각 그룹 별로 비율의 전체 합은 1이 되어야 한다.

from sklearn.preprocessing import OneHotEncoder
import seaborn as sns
titanic=sns.load_dataset("titanic")
titanic



survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [29]:
#pd.pivot_table(data, index='grade',columns='prod_cd',values='pch_amt', aggfunc=np.sum)
bins=[1,15,25,35,60,99]
labels=["미성년자","청년","중년","장년","노년"]

categ=pd.cut(titanic['survived'], bins, labels=labels)
categ

titanic['age'] = pd.cut(titanic["Age"],bins,labels=labels)
titanic.sort_values(by='Survived')
survived = titanic[titanic['Survived'] == 1]['age'].value_counts(0)
died = titanic[titanic['Survived'] == 0]['age'].value_counts(0)

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
      ... 
886    NaN
887    NaN
888    NaN
889    NaN
890    NaN
Name: survived, Length: 891, dtype: category
Categories (5, object): [미성년자 < 청년 < 중년 < 장년 < 노년]

In [ ]:
#실수, 데이터 -> 카테고리화
#cut(실수 값의 경계 지정)
#qcut(똑같은 구간으로 나눌때)
ages=[0,2,10,21,23,37,31,61,20,42,32,100]
bins=[1,15,25,35,60,99]
labels=["미성년자","청년","중년","장년","노년"]

cats=pd.cut(ages, bins, labels=labels) #labels 속성(왼), 이름(오)
cats


In [ ]:
data=np.random.randn(100)
data
cats=pd.qcut(data, 4, labels=["Q1","Q2","Q3","Q4"])
cats
pd.value_counts(cats)

In [25]:
re_list5=list(map(str,input("Reverse list: ")))
for char in range(len(re_list5)-1, -1,-1):
    print(re_list5[char],end=" ")

Reverse list: 214sd
d s 4 1 2 

In [10]:
a = map(int,input("Reverse list: "))

Reverse list: 123qweasd


In [11]:
a

In [ ]:
# 1. 문자열 거꾸로 출력하는 4가지
 
text = 'lectopia'
 
# 1번 : range 사용
for i in range(len(text)-1,-1,-1):
    print(text[i],end=' ')
print()
# 2번 : while문
cnt = len(text)
while(cnt>0):
    cnt -=1
    print(text[cnt], end=' ')
print()
 
# 3번 : 슬라이싱
for i in text[::-1]:
    print(i,end=' ')
print()
 
# 4번 : reversed
for i in reversed(text):
    print(i, end= ' ')
print()
 
 
# 슬라이싱 한다는것은 원본을 복사한다는것,
 참조하는것이 아니라 원본을 복사해서 당겨오게됨 
그래서 슬라이싱은 다른 방법에 비해 성능이 다소 떨어짐
# 성능이 가장 좋은것은 1번 2번이다.

# 2. 리스트 거꾸로 뒤집기
b = [0,1,2,3,4]
 
size = len(b)
for i in range(size//2):
    b[i],b[size-1-i] = b[size-1-i], i
print(b)
 
# 3. 선택 정렬로 정렬
 
def findMaxPos(ary, size):
    pos = 0
    for i in range(1,size):
        if ary[pos] < ary[i]:
            pos = i
    return pos
 
def selectionSort(ary, size):
    for i in range(size,1,-1):
        tmp = findMaxPos(ary,i)
        ary[tmp], ary[i-1] = ary[i-1], ary[tmp]
 
selectionSort(b,5)
print(b)



In [21]:
b='power'
a= list(range(len(b),-1,-1))
a

[5, 4, 3, 2, 1, 0]

[5, 4, 3, 2, 1, 0]

In [15]:
a[-1]

-1

-1

In [ ]:
data = pd.read_csv("C:/Users/student/수업 및 과제/데이터 분석/과제/data/train.csv")



bins = [1, 15, 25, 35, 60, 99]
labels = ["미성년자", "청년", "중년", "장년", "노년"]
data['Age_cats'] = pd.cut(data.Age, bins, labels=labels)


data = data.dropna(axis=0)
data_fix = (data['Age_cats'].groupby(data['Survived']).value_counts() / data['Age_cats'].groupby(data['Survived']).size()).unstack()


data_fix['Total'] = data_fix.sum(axis=1)